### ISSUE TITLE
San Antonio Institute for Women’s Health warns patients personal data compromised in network hack

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10001]
http://www.mysanantonio.com/business/local/article/Institute-for-Women-s-Health-notifies-patients-11943303.php

**Comment by swidup** [comment]
https://www.ifwh.org/en/newsroom/

**Comment by swidup** [comment]
http://www.healthcareitnews.com/news/san-antonios-largest-ob-gyn-provider-breached-keylogger-malware

**Comment by keithbreland** [comment]
8/29
