### ISSUE TITLE
Drugs storm hits football: Russian hackers claim nine players in Britain failed tests to leave sport's clean image in tatters

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10017]
http://www.dailymail.co.uk/sport/sportsnews/article-4812334/Fancy-Bears-hackers-leak-football-drug-use.html

**Comment by swidup** [comment]
http://www.telegraph.co.uk/football/2017/08/22/football-association-disappointed-fancy-bears-leak-anti-doping/

**Comment by keithbreland** [comment]
9/14
