### ISSUE TITLE
Data breach at Mid-Michigan Physicians compromised patient records

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10029]
http://www.lansingstatejournal.com/story/news/local/2017/08/25/lansing-data-breach-mid-michigan-physicians/602183001/

**Comment by swidup** [comment]
http://www.wilx.com/content/news/Data-breach-at-Mid-Michigan-Physicians-Practice-441746563.html

**Comment by keithbreland** [comment]
8/29
