### ISSUE TITLE
NHS Lanarkshire hit by cyber attack cancels operations and asks patients not to come to hospital 'unless it is essential'

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10040]
http://www.independent.co.uk/news/uk/home-news/cyber-attacks-uk-nhs-lanarkshire-scotland-hospitals-affected-patients-operations-ransomware-wannacry-a7913896.html

**Comment by swidup** [comment]
https://stv.tv/news/west-central/1396611-cyber-attack-which-hit-nhs-board-was-ransomware/

**Comment by keithbreland** [comment]
9/14
