### ISSUE TITLE
Kaiser Permanente says 600 Riverside area members affected by data breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10073]
http://www.pe.com/2017/08/30/kaiser-permanente-says-600-riverside-area-members-affected-by-data-breach/

**Comment by swidup** [comment]
http://www.beckershospitalreview.com/cybersecurity/kaiser-permanente-notifies-600-members-of-data-breach-after-email-mix-up.html

**Comment by keithbreland** [comment]
10-30
