### ISSUE TITLE
Computer virus at Alaska OCS offices may have put individual's personal information at risk

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10082]
http://www.webcenter11.com/content/news/Computer-virus-at-Alaska-OCS-offices-may-have-put-individuals-personal-information-at-risk--442700573.html

**Comment by swidup** [comment]
http://www.newsminer.com/news/alaska_news/state-more-than-may-have-had-info-stolen-in-ocs/article_507afc22-8f84-11e7-acdf-1bcb495bb9f8.html

**Comment by swidup** [comment]
http://www.healthcareitnews.com/news/alaska-dhss-facing-potential-breach-after-two-trojan-malware-attacks

**Comment by cdander** [comment]
9/20
