### ISSUE TITLE
Passwords to Over a Half Million Car Tracking Devices Leaked Online - SVR Tracking

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10187]
https://gizmodo.com/passwords-to-access-over-a-half-million-car-tracking-de-1818624272

**Comment by swidup** [comment]
http://www.digitaljournal.com/tech-and-science/technology/data-from-540-thousand-vehicle-tracking-devices-leaked-online/article/503203

**Comment by keithbreland** [comment]
10-31
