### ISSUE TITLE
Morehead Memorial Hospital: Data breach may have leaked patient and employee information

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10192]
https://www.databreaches.net/nc-morehead-memorial-hospital-data-breach-may-have-leaked-patient-and-employee-information/

**Comment by swidup** [comment]
https://www.bizjournals.com/triad/news/2017/09/15/morehead-memorial-hospital-data-breach-may-have.html

**Comment by keithbreland** [comment]
10/23
