### ISSUE TITLE
Breach at Sonic Drive-In May Have Impacted Millions of Credit, Debit Cards

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10208]
https://krebsonsecurity.com/2017/09/breach-at-sonic-drive-in-may-have-impacted-millions-of-credit-debit-cards/

**Comment by swidup** [comment]
http://www.ibtimes.com/sonic-hack-restaurant-confirms-malware-stole-customer-credit-cards-2597810

**Comment by keithbreland** [comment]
11-03
