### ISSUE TITLE
Latest skimming devices found at two Fauquier gas stations - WI-Not Stop

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10210]
http://www.insidenova.com/news/crime_police/latest-skimming-devices-found-at-two-fauquier-gas-stations/article_5643668e-a394-11e7-8558-87d0e0c2ce9d.html

**Comment by swidup** [comment]
http://www.fauquiernow.com/index.php/fauquier_news/article/fauquier-card-skimming-devices-found-in-bealeton-opal-2017

**Comment by keithbreland** [comment]
The second link is no longer active. 10/12
