### ISSUE TITLE
Hyatt Hotels Suffers 2nd Card Breach in 2 Years

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10293]
https://krebsonsecurity.com/2017/10/hyatt-hotels-suffers-2nd-card-breach-in-2-years/

**Comment by swidup** [comment]
https://www.reuters.com/article/us-hyatt-hotels-cyber/hyatt-hotels-discovers-card-data-breach-at-41-properties-idUSKBN1CH2WP

**Comment by cdander** [comment]
10/18
