### ISSUE TITLE
VERIS JSON data not compliant with JSON spec.

### ISSUE THREAD

**Issue by walkerandco** [vz-risk/VCDB#10292]
The JSON files in this repository are not strictly following the JSON specification. The specification is here: [https://tools.ietf.org/html/rfc7159](https://tools.ietf.org/html/rfc7159)

JSON is intended to store keys and values explicitly, not within the name of a sub-object. For example, for "actors", we have "actors.internal" "actors.external" "actors.partner" when in fact it should be e.g. {actors: {type: "internal"}}. There are many others, such as "action.misuse", "action.hacking". These should be stored in keys and values, not sub-object names because the subobject name is actually holding data, which is not allowed in the JSON spec.

This is important because it makes the JSON data very difficult to parse in native Javascript without hacky code, whereas JS is designed to be very simply to interface with proper JSON. When key,value pairs are stored in object names, they become conflated and have to be manually separated in javascript on a context-dependant basis. If key,value pairs were properly implemented, hacky code would not be necessary because the object names would be predictable by design (there is a schema) and to add to that the key for the value would be constant, thus reducing the need to produce code to anticipate the likely value of the key in the k,v pair.

I'm writing a powerful visual analytics library just for VCDB in node.js, parsing the json schema has been a nightmare as a result of the above.

I suggest that the JSON schema for VERIS is changed to reflect this and remove the bad practice of including key,value pairs in object names. I would be happy to run the files through a script to implement the changes and submit a pull request.

**Comment by gdbassett** [comment]
Unfortunately, the current [VERIS schema](http://github.com/vz-risk/veris) is engrained in a large amount of tooling and data, (basically the entire DBIR workflow).  The effort to change it would be impractical.  Additionally, the current schema works rather well for tabular analysis (i.e. converting into a table of data) except for specific parts where lists of objects exist.

I can tell you that in the parsing we do, to get to intermediate enumerations (such as action.Hacking/Malware/etc), we actually parse down to the variety/vector level which are required and then, in a record, if they exist, also add the intermediate enumeration.  In other words, if there is a value for action.hacking.variety, we can infer that action.Hacking is True for that record.  This is primarily an issue for action, actor, asset, attribute, and discovery_method I believe.

**Comment by walkerandco** [comment]
@gdbassett  That's a terrible shame, I think that just because it works now shouldn't be a ground not to improve the schema in the future. Without complying with the JSON specification, it is very difficult for third-party developers outside of Verizon RISK to extend the schema or create third-party tooling outside of that team without having to hack around the schema. I could probably have reduced my application by 200+ lines of code if it was properly standardised to the spec.

I think the best course is for me to discuss this with my colleagues and it may be that the project should be forked with a separate schema for third-party developers wishing to integrate the VCDB and I could maintain the separate repository.
