### ISSUE TITLE
Queens men charged with ATM skimming - Santander Bank, TD Bank, Capitol One, Teachers Federal Credit Union

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10296]
http://www.qchron.com/editions/central/queens-men-charged-with-atm-skimming/article_e5757036-3535-5259-b8de-c90b0c67d6f3.html

**Comment by swidup** [comment]
http://qns.com/story/2017/10/09/woodside-men-charged-installing-atm-bank-skimming-devices-across-queens/

**Comment by keithbreland** [comment]
10-26
