### ISSUE TITLE
Ashland clinic notifies 1,600 patients after ransomware incident - Namaste Health Care

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10317]
https://www.databreaches.net/ashland-clinic-notifies-1600-patients-after-ransomware-incident/

**Comment by swidup** [comment]
http://www.newstribune.com/news/local/story/2017/oct/14/security-breach-reported-at-ashland-clinic/695646/

**Comment by cdander** [comment]
10/18
