### ISSUE TITLE
Glamorous globe-trotting life of married police couple who sold details of thousands of car crash victims to cold callers for £363,000

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10328]
http://www.dailymail.co.uk/news/article-4960390/Glamorous-globe-trotting-life-married-police-couple.html

**Comment by swidup** [comment]
http://www.mirror.co.uk/news/uk-news/police-officer-sold-car-crash-11310818

**Comment by keithbreland** [comment]
10/23
