### ISSUE TITLE
Massive South African database leak reveals private data of 30 million people

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10339]
https://mybroadband.co.za/news/security/233581-massive-south-african-database-leak-reveals-private-data-of-30-million-people.html

**Comment by swidup** [comment]
http://www.fin24.com/Tech/News/millions-of-south-africans-personal-information-may-have-been-leaked-online-20171017

**Comment by keithbreland** [comment]
10-30

**Comment by swidup** [comment]
http://www.huffingtonpost.co.za/pieter-van-der-merwe/sa-s-biggest-data-leak-and-the-group-of-realtors-responsible_a_23259902/

**Comment by swidup** [comment]
https://www.timeslive.co.za/news/south-africa/2017-10-18-top-real-estate-company-admits-to-being-unwitting-source-of-countrys-largest-personal-data-breach/
