### ISSUE TITLE
An Apple engineer showed his daughter the new iPhone X. Now, she says, he’s fired.

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10358]
https://www.recode.net/2017/10/29/16567244/apple-engineer-fired-iphone-x-daughter-secret-product-launch

**Comment by swidup** [comment]
http://www.telegraph.co.uk/technology/2017/10/30/apple-fires-employee-daughters-video-new-iphone-x-goes-viral/

**Comment by keithbreland** [comment]
11-03
