### ISSUE TITLE
Hackers have stolen data from a cosmetic surgery clinic used by the rich and famous - London Bridge Plastic Surgery

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10356]
http://metro.co.uk/2017/10/24/hackers-have-stolen-data-from-a-cosmetic-surgery-clinic-used-by-the-rich-and-famous-7023893/

**Comment by swidup** [comment]
https://www.christianpost.com/news/hacker-steals-patients-sensitive-photos-and-records-from-top-london-plastic-surgery-clinic-204274/

**Comment by cdander** [comment]
12/8
