### ISSUE TITLE
Jury convicts former Cumming Police sergeant of accepting bribes and computer fraud

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10355]
https://www.justice.gov/usao-ndga/pr/jury-convicts-former-cumming-police-sergeant-accepting-bribes-and-computer-fraud

**Comment by swidup** [comment]
http://www.cbs46.com/story/36716389/former-police-officer-convicted-for-accepting-bribes-computer-fraud

**Comment by keithbreland** [comment]
11-01
