### ISSUE TITLE
Last Year the Panama Papers, This Year the Bermuda Briefs? - Appleby

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10366]
https://www.jdsupra.com/legalnews/last-year-the-panama-papers-this-year-61947/

**Comment by swidup** [comment]
http://m.jamaicaobserver.com/news/law-firm-fears-breach-of-wealthy-clients-8217-data_115205?profile=1338&template=MobileArticle

**Comment by swidup** [comment]
https://economictimes.indiatimes.com/news/politics-and-nation/data-hack-at-appleby-rattles-indians-with-offshore-accounts/articleshow/61523086.cms

https://www.japantimes.co.jp/news/2017/11/06/world/new-paradise-papers-data-leak-links-hatoyama-bermuda-firm-u-s-commerce-chief-putin-biz-benefits/

https://www.irishtimes.com/business/lost-what-is-the-icij-s-paradise-papers-project-1.3280704    "The bulk of the documents come from the Appleby offshore law firm and its offshore fiduciary arm, which is now called Estera, but the leaked material also includes documents from the Asiaciti Trust corporate services firm in Singapore, and a number of offshore or secrecy jurisdictions."

**Comment by Spitler** [comment]
Part of 2016 Panama Papers breach. Already coded up and this provides no threat action or other details
