### ISSUE TITLE
We knew about data theft since February, Malaysian dental group now says - Malaysian Dental Association 

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10380]
http://www.todayonline.com/world/asia/we-knew-about-data-theft-february-dental-group-now-says

**Comment by swidup** [comment]
http://www.freemalaysiatoday.com/category/nation/2017/11/01/minister-mcmc-may-have-identified-sources-of-massive-data-breach/  "Reports said that 81,309 records from the Malaysian Medical Council, Malaysian Medical Association (MMA) and Malaysian Dental Association were also leaked."

**Comment by cdander** [comment]
12/8
