### ISSUE TITLE
BIGGEST ANIME STREAMING SITE JUST GOT HACKED, IT DOWNLOADED MALWARE TO USER’S DEVICES - Crunchyroll

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10402]
https://otakukart.com/news/crunchyroll-hacked/

**Comment by cdander** [comment]
Below is an update to the crunchyroll hack:

https://www.engadget.com/2017/11/04/crunchyroll-hack-tried-to-infect-visitors-with-malware/

**Comment by cdander** [comment]
11/8
