### ISSUE TITLE
Suspects using skimmers on ATMs steal thousands in Ramsey, Dakota counties -  City County Credit Union

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10423]
http://www.startribune.com/suspects-using-skimmers-on-atm-machines-steal-thousands-in-ramsey-dakota-counties/453100843/

**Comment by swidup** [comment]
http://www.twincities.com/2017/10/25/shoreview-atms-hit-with-credit-card-skimmers-suspects-caught-on-camera/

**Comment by cdander** [comment]
11/8

**Comment by cdander** [comment]
11/8

**Comment by cdander** [comment]
11/8

**Comment by cdander** [comment]
11/8

**Comment by cdander** [comment]
11/8
