### ISSUE TITLE
Malaysia's CIMB says backup tapes containing banking customer data lost

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10469]
http://www.reuters.com/article/us-cimb-data/malaysias-cimb-says-backup-tapes-containing-banking-customer-data-lost-idUSKBN1DD19O?il=0

**Comment by swidup** [comment]
http://www.themalaymailonline.com/malaysia/article/bank-negara-says-aware-of-cimbs-lost-data-tapes#cBRDhGQ2BJJBEtHo.97

**Comment by cdander** [comment]
11/21
