### ISSUE TITLE
Drone maker DJI left its private SSL, firmware keys open to world+dog on GitHub FOR YEARS

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10484]
https://www.theregister.co.uk/2017/11/16/dji_private_keys_left_github/

**Comment by swidup** [comment]
https://arstechnica.com/information-technology/2017/11/dji-left-private-keys-for-ssl-cloud-storage-in-public-view-and-exposed-customers/

**Comment by cdander** [comment]
12/4

**Comment by swidup** [comment]
https://forum.dji.com/thread-125010-1-1.html
