### ISSUE TITLE
‘Jeopardy!’ champion Jass accused of hacking emails - Adrian College

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10624]
http://www.lenconnect.com/news/20171205/jeopardy-champion-jass-accused-of-hacking-emails

**Comment by gdbassett** [comment]
https://www.insidehighered.com/news/2018/07/23/former-adrian-college-professor-pleads-guilty-hacking-college-email-accounts

**Comment by gdbassett** [comment]
https://www.freep.com/story/news/local/michigan/2018/07/20/stephanie-jass-jeopardy-adrian-college/809384002/
