### ISSUE TITLE
Stanislaus County computers held ransom by hackers - Stanislaus County Behavioral Health and Recovery Services

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10677]
http://www.modbee.com/news/article190077164.html

**Comment by swidup** [comment]
https://healthitsecurity.com/news/pa-security-breach-from-missing-external-hard-drive-affects-4.1k

**Comment by planglois925** [comment]
http://www.stancounty.com/news-room/news-releases/news-2017/pdf/press-release-20171215-bhrs.pdf
