### ISSUE TITLE
PHI IMPROPERLY TRANSMITTED TO BUSINESS ASSOCIATE - RoxSan Pharmacy

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#10975]
https://healthitsecurity.com/news/36k-notified-of-potential-healthcare-data-breach-from-mailing-error

**Comment by jasoncmiller79** [comment]
https://www.prnewswire.com/news-releases/roxsan-pharmacy-notifies-patients-of-potential-breach-of-unsecured-personal-information-300598196.html
