### ISSUE TITLE
St. Louis Community College investigating possible student data breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#11055]
http://www.kmov.com/story/37628377/st-louis-community-college-investigating-possible-student-data-breach

**Comment by swidup** [comment]
https://www.ksdk.com/article/news/local/stlccs-data-breach-has-students-concerned/63-e6904f06-47b2-4bb4-ade7-8fa8fdbf62d8

**Comment by gdbassett** [comment]
two breaches.
