### ISSUE TITLE
NY Insurer Pays Nearly $600K to Resolve Data Breach That Exposed SSNs - EmblemHealth

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#11151]
https://www.law.com/newyorklawjournal/2018/03/16/ny-insurer-pays-nearly-600k-to-resolve-data-breach-that-exposed-ssns/

**Comment by jasoncmiller79** [comment]
https://ag.ny.gov/press-release/ag-schneiderman-announces-575000-settlement-emblemhealth-after-data-breach-exposed
