### ISSUE TITLE
Wilmette police: Walgreens employees spot ATM skimming device

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#11209]
http://www.chicagotribune.com/suburbs/wilmette/news/ct-wml-blotter-tl-0405-story.html

**Comment by jasoncmiller79** [comment]
Link unavailable;  a Google search did not reveal any information on this potential incident

**Comment by jasoncmiller79** [comment]
Link unavailable;  a Google search did not reveal any information on this potential incident
