### ISSUE TITLE
Cyberattack knocks Energy Services Group offline

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#11241]
https://www.scmagazine.com/cyberattack-knocks-energy-services-group-offline/article/755983/

**Comment by swidup** [comment]
https://www.bloomberg.com/news/articles/2018-04-04/cyberattack-bleeds-into-utility-space-as-duke-sees-billing-delay

**Comment by dhylender** [comment]
I coded this event a couple of weeks ago. Closing it out.
