### ISSUE TITLE
Timco Aviation Data Breach Class Action Settlement (W-2)

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#11325]
http://www.classactionrebates.com/settlements/timco-aviation/

**Comment by jasoncmiller79** [comment]
https://www.databreaches.net/timco-aviation-services-settles-class-action-lawsuit-by-employees-over-2016-w-2-breach/

http://www.kathrynsreport.com/2018/04/timco-aviation-data-breach-class-action.html
