### ISSUE TITLE
AIG unit had duty to defend hotel firm under computer act - WoodSpring Hotels LLC

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#11363]
http://www.businessinsurance.com/article/20180507/NEWS06/912321094/AIG-unit-had-duty-to-defend-hotel-firm-under-Federal-Computer-Fraud-and-Abuse-Ac

**Comment by swidup** [comment]
https://www.law.com/texaslawyer/2018/05/09/mckool-smith-attorney-convinces-delaware-court-that-10m-policy-covers-trade-secrets-case/

**Comment by jasoncmiller79** [comment]
https://courts.delaware.gov/Opinions/Download.aspx?id=272320
