### ISSUE TITLE
Parkesburg councilman, bank exec charged in $100K embezzlement scam - Downingtown National Bank 

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#11667]
http://www.delcotimes.com/article/DC/20180626/NEWS/180629737

**Comment by B-byrd** [comment]
Previous link remove or incorrect path. 

Correct Link https://www.delcotimes.com/news/morning-briefing-councilman-charged-in-big-embezzlement-phillies-strike-out/article_fd35e791-50b5-53eb-a093-16965d6e6b4f.html
