### ISSUE TITLE
Grand juror could go to prison after pleading guilty to disclosing indictment on Facebook Messenger

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#11685]
http://www.abajournal.com/news/article/grand_juror_could_go_to_prison_after_pleading_guilty_to_disclosing_indictme/?utm_source=maestro&utm_medium=email&utm_campaign=weekly_email

**Comment by jasoncmiller79** [comment]
https://www.justice.gov/usao-sdfl/pr/former-grand-juror-pleads-guilty-obstruction-justice
