### ISSUE TITLE
Key Brexit documents left on Eurostar train in embarrassing security bungle

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#11721]
https://www.mirror.co.uk/news/politics/key-brexit-documents-left-eurostar-12829601

**Comment by swidup** [comment]
https://www.thetimes.co.uk/article/brexit-almost-derailed-as-theresa-may-aide-oliver-robbins-briefings-left-on-eurostar-train-tc2nvjm2f

**Comment by jasoncmiller79** [comment]
https://www.express.co.uk/news/politics/982383/brexit-news-theresa-may-eurostar-eu-olly-robbins
