### ISSUE TITLE
Thousands of patients' data stolen after Children's Mercy employees fall for scam

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#11730]
https://www.kansascity.com/news/business/health-care/article214266159.html

**Comment by swidup** [comment]
https://www.secureworldexpo.com/industry-news/kids-information-phishing-attack

**Comment by jasoncmiller79** [comment]
https://www.hipaajournal.com/childrens-mercy-hospital-sued-for-63000-record-data-breach/

Added article from duplicate Issue #11784
