### ISSUE TITLE
Court Finds Travelers Crime Policy Covers Money Transfer Loss Due to Email Spoofing

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#11807]
https://www.insurancejournal.com/news/national/2018/07/17/495389.htm

**Comment by jasoncmiller79** [comment]
**Updated Link**
(American Tooling Center, Inc. v. Travelers Casualty and Surety).
https://www.insurancejournal.com/app/uploads/2018/07/American-Tooling-v-Travelers.pdf
