### ISSUE TITLE
Russian researchers ‘leaked hypersonic secrets’ to the Wes

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#11842]
https://www.thetimes.co.uk/article/russian-researchers-leaked-hypersonic-secrets-to-the-west-lfm2pzwg2

**Comment by swidup** [comment]
https://www.thetimes.co.uk/article/russian-scientist-charged-with-treason-over-weapons-leak-5kqfkqfk2

**Comment by jasoncmiller79** [comment]
https://www.rt.com/news/433803-russia-hypersonic-missiles-leak/
