### ISSUE TITLE
‘I’m not a tech-savvy person’: The 63-year-old Telstra user who managed to access customer details

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#11885]
http://en.brinkwire.com/news/im-not-a-tech-savvy-person-the-63-year-old-telstra-user-who-managed-to-access-customer-details/

**Comment by jasoncmiller79** [comment]
http://www.dailymail.co.uk/news/article-6001527/Im-not-tech-savvy-person-63-year-old-Telstra-user-managed-access-customer-details.html
