### ISSUE TITLE
Thousands of SA children's medical test results online for 13 years: SA Health

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#11946]
http://www.abc.net.au/news/2018-08-04/sa-childrens-medical-records-published-online-13-years/10073730

**Comment by swidup** [comment]
https://www.9news.com.au/videos/cjkf6n3l8001a0go5b9dqerkv/sa-health-forced-to-apologise-for-privacy-breach

**Comment by jasoncmiller79** [comment]
https://www.adelaidenow.com.au/news/south-australia/7000-patient-records-from-womens-and-childrens-hospital-exposed-online-in-embedded-data/news-story/0281a9d60187959db721ffefc9dac5c8

**Comment by jasoncmiller79** [comment]
https://latesthackingnews.com/2018/08/05/data-breach-at-womens-and-childrens-hospital-exposed-childrens-records-online/

**Comment by jasoncmiller79** [comment]
Added articles from duplicate entry 11941
