### ISSUE TITLE
Data Breach At Women’s and Children’s Hospital Exposed Children’s Records Online

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#11941]
https://latesthackingnews.com/2018/08/05/data-breach-at-womens-and-childrens-hospital-exposed-childrens-records-online/

**Comment by swidup** [comment]
https://www.adelaidenow.com.au/news/south-australia/7000-patient-records-from-womens-and-childrens-hospital-exposed-online-in-embedded-data/news-story/0281a9d60187959db721ffefc9dac5c8

**Comment by swidup** [comment]
https://www.9news.com.au/national/2018/08/04/18/38/south-australia-patients-medical-rescords-privacy-breach-sa-health-apology

**Comment by jasoncmiller79** [comment]
Duplicate of 11946
