### ISSUE TITLE
Arik Air suffers massive leak that may put over 600,000 customers' data in danger

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#12509]
https://www.pulse.ng/bi/tech/arik-air-suffers-massive-leak-in-customers-data-id9050897.html

**Comment by swidup** [comment]
https://www.usnews.com/news/best-states/new-mexico/articles/2018-10-30/ex-air-force-airman-in-new-mexico-accused-of-computer-fraud

**Comment by dhylender** [comment]
conflicting and insufficient information to code.
