### ISSUE TITLE
Public slams Finnish Transport Safety Agency for privacy breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#12675]
https://yle.fi/uutiset/osasto/news/public_slams_finnish_transport_safety_agency_for_privacy_breach/10545986

**Comment by swidup** [comment]
https://yle.fi/uutiset/osasto/news/trafi_boss_resigns_over_privacy_breach/10553376 
    "IOI_executive_churn": "Yes",

**Comment by planglois925** [comment]
invalide
