### ISSUE TITLE
Graham Police Believe At Least Two People Had Cards Skimmed At ATM - Cash Points

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#13122]
https://www.wfmynews2.com/video/news/local/graham-police-believe-at-least-two-people-had-cards-skimmed-at-atm/83-c7edb903-aa5e-4a63-91bc-324eff70628a

**Comment by gdbassett** [comment]
report is based on a single person's anecdotal story.  Police didn't find the skimmer at the ATM.  Closing for lack of information
