### ISSUE TITLE
Ex-employee sued by firm after falling for BEC scam - Peebles Media Group

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#13130]
https://www.cso.com.au/article/657653/ex-employee-sued-by-firm-after-falling-bec-scam/

**Comment by alexcpsec** [comment]
https://www.bbc.com/news/uk-scotland-glasgow-west-47161340

**Comment by alexcpsec** [comment]
847964b2-ce0e-4b5b-9ce8-085c933fe387.json
