### ISSUE TITLE
Thousands of Arizonans hit in Medicaid agency’s data breach - Arizona Health Care Cost Containment System

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#13250]
http://ktar.com/story/2477709/thousands-of-arizonans-hit-in-medicaid-agencys-data-breach/

**Comment by swidup** [comment]
https://www.beckershospitalreview.com/cybersecurity/arizona-medicaid-alerts-3-100-patients-of-privacy-breach.html

**Comment by jpsturgis** [comment]
[https://www.azcentral.com/story/news/local/arizona-health/2019/03/11/arizona-medicaid-program-ahcccs-warns-breach-personal-health-information/3130904002/](url)

**Comment by jpsturgis** [comment]
[https://www.azahcccs.gov/shared/News/PressRelease/breach.html](url)
