### ISSUE TITLE
Indian govt agency left details of millions of pregnant women exposed online

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#13347]
https://www.zdnet.com/article/indian-govt-agency-left-details-of-millions-of-pregnant-women-exposed-online/

**Comment by jpsturgis** [comment]
[https://securitydiscovery.com/large-privacy-breach-in-india/](url)

**Comment by jpsturgis** [comment]
[https://www.cisomag.com/unprotected-server-exposes-details-of-12-5-million-women/](url)
