### ISSUE TITLE
Researcher: Data Leaked for 300 Million Truecaller Users

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#13526]
https://www.databreachtoday.in/researcher-data-leaked-for-300-million-truecaller-users-a-12519

**Comment by gdbassett** [comment]
breach was re-reported May 2020 as well: https://www.livemint.com/technology/tech-news/truecaller-denies-breach-after-data-of-4-75-crore-indians-appear-on-dark-web-11590562442362.html
