### ISSUE TITLE
139 Million Users Hit in Canva Data Breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#13527]
https://www.tomsguide.com/us/canva-data-breach,news-30165.html

**Comment by swidup** [comment]
https://www.zdnet.com/article/australian-tech-unicorn-canva-suffers-security-breach/

**Comment by swidup** [comment]
https://siliconangle.com/2019/05/27/139m-customer-records-stolen-hack-popular-graphic-design-tool-site-canva/

**Comment by swidup** [comment]
https://smallbiztrends.com/2019/06/change-passwords-regularly.html

**Comment by gdbassett** [comment]
https://support.canva.com/contact/customer-support/may-24-security-incident-faqs/
