### ISSUE TITLE
Orlando computer-security company sues, claiming blackmail, theft of trade secrets - TorGuard

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#13550]
https://www.orlandosentinel.com/business/os-bz-vpn-lawsuit-blackmail-20190529-l2zywgjkfjdtpj4vk2wm7qfyba-story.html

**Comment by swidup** [comment]
https://www.vpncompare.co.uk/torguard-nordvpn-courtroom-showdown/

**Comment by planglois925** [comment]
These are all allegations at this point
