### ISSUE TITLE
 Kingman Regional Medical Center investigating potential breach of PHI

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#13669]
https://www.databreaches.net/kingman-regional-medical-center-investigating-potential-breach-of-phi/

**Comment by swidup** [comment]
https://kdminer.com/news/2019/jun/08/krmc-website-shut-down-april-possible-security-bre/

**Comment by gdbassett** [comment]
https://kjzz.org/content/1011936/kingman-medical-center-fixing-website-left-1100-patients-data-vulnerable
