### ISSUE TITLE
Oregon Construction Contractors Board reports data breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#13672]
https://www.databreaches.net/oregon-construction-contractors-board-reports-data-breach/

https://www.ktvz.com/news/oregon-construction-contractors-board-reports-data-breach/1078851398

**Comment by gdbassett** [comment]
https://www.oregon.gov/CCB/Documents/pdf/JUSTICE-9596167-v1-CCB_-_Data_Disclosure_News_Release.pdf
