### ISSUE TITLE
Hassan Likely Didn’t Notify Constituents Whose Data May Have Been Exposed, Despite Pushing Law Requiring It For Companies

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#13703]
https://dailycaller.com/2019/06/30/maggie-hassan-hacked-identity-risk/

**Comment by swidup** [comment]
https://www.thenewamerican.com/usnews/congress/item/32746-senator-whose-computers-were-hacked-appears-not-to-have-notified-affected-constituents

**Comment by gdbassett** [comment]
Not using previous articles which appear to have political bias.  Using the following reference:
https://www.bostonglobe.com/metro/2019/04/07/former-hassan-staffer-pleads-guilty-stealing-data/VYkyDl6wb24wNthDK99TMM/story.html

**Comment by gdbassett** [comment]
https://www.bostonglobe.com/metro/2019/04/07/former-hassan-staffer-pleads-guilty-stealing-data/VYkyDl6wb24wNthDK99TMM/story.html
