### ISSUE TITLE
Office.com Defaced by Syrian Electronic Army

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#1378]
http://blogs.csoonline.com/malwarecybercrime/2936/officecom-defaced-syrian-electronic-army?utm_content=bufferfea8d&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

SEA is having a wonderful time playing with M$ these days.  This is the third in recent memory.

**Comment by Usaar** [comment]
http://www.networkworld.com/article/2173579/byod/syrian-electronic-army-hacks-microsoft--39-s-office-blogs-site.html

New link because the current link is outdated.

**Comment by Usaar** [comment]
Submitted
