### ISSUE TITLE
122,000 Providence Health Plan customers may be affected by data breach - Dominion National

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#14022]
https://www.oregonlive.com/news/2019/08/122000-providence-health-plan-customers-may-be-affected-by-data-breach.html

**Comment by swidup** [comment]
http://bronxvoice.com/122000-providence-health-plan-customers-may-be-affected-by-data-breach-oregonlive-com/

**Comment by dhylender** [comment]
I deleted the second link as google notified it was suspicious.
