### ISSUE TITLE
Security breach brings down shutters on 7Pay

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#14068]
https://www.databreaches.net/security-breach-brings-down-shutters-on-7pay/

https://www.mobileworldlive.com/money/news-money/security-breach-brings-down-shutters-on-7pay/

**Comment by gdbassett** [comment]
https://www.theverge.com/2019/7/6/20684386/7-eleven-japan-shut-mobile-payments-app-7pay-security-flaw-cybersecurity
