### ISSUE TITLE
Meridian Community College Provides Notice of Data Incident

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#14082]
https://finance.yahoo.com/news/meridian-community-college-provides-notice-000000176.html

**Comment by swidup** [comment]
http://www.spamfighter.com/News-22425-Notice-about-a-recent-data-incident-provided-by-Meridian-Community-College.htm

**Comment by gdbassett** [comment]
Article lacks information as to what actions happened, whether they were malicious, and  if any data was comromised.
