### ISSUE TITLE
198 Million Car-Buyer Records Exposed Online for All to See - Dealer Leads 

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#14148]
https://threatpost.com/198m-car-buyer-records-exposed-online/148231/

**Comment by swidup** [comment]
https://www.scmagazine.com/home/security-news/misconfigured-database-exposes-198m-records-on-prospective-auto-buyers/

**Comment by gdbassett** [comment]
https://securitydiscovery.com/dealer-leads/
