### ISSUE TITLE
Data of 24.3 million Lumin PDF users shared on hacking forum

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#14179]
https://www.zdnet.com/article/data-of-24-3-million-lumin-pdf-users-shared-on-hacking-forum/

**Comment by gdbassett** [comment]
This is a wierd one that strattles the line between being coded as a misconfiguration error and a malicious attack by the 'hacker'.  The second breach in it is clearly a 'hacking' attack as the actor deleted the database.
