### ISSUE TITLE
'I don't know who you made angry...' Vegas coach told Mountain Pointe coach someone leaked gameplan

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#14185]
https://www.12news.com/article/news/local/valley/vegas-coach-told-mountain-pointe-coach-someone-leaked-gameplan/75-0a1b3be4-ddcc-493b-80d6-57c20658f874

**Comment by swidup** [comment]
https://www.12news.com/article/news/local/valley/newly-obtained-emails-might-show-why-ex-mountain-pointe-coach-allegedly-leaked-game-information/75-5a1919a7-6c6b-4420-8942-a2430c7f0be4

**Comment by swidup** [comment]
https://www.azfamily.com/news/district-fires-mountain-pointe-hs-coach-who-shared-secrets-with/article_a7bcf5ee-e56d-11e9-b441-9b9e6268a3df.html

**Comment by gdbassett** [comment]
Does not involve computers.
