### ISSUE TITLE
Report: Scotiabank exposed source code and credentials on GitHub repositories

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#14192]
https://www.scmagazine.com/home/security-news/data-breach/report-scotiabank-exposed-source-code-and-credentials-on-github-repositories/

**Comment by swidup** [comment]
https://www.theregister.co.uk/2019/09/18/scotiabank_code_github_leak/

**Comment by Nisza25** [comment]
https://www.itworldcanada.com/article/scotiabank-source-code-credentials-found-open-on-github-news-report/421992
