### ISSUE TITLE
Pakistani Hackers Upload Defacement Page to Website of Indian Railways

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#1420]
http://news.softpedia.com/news/Pakistani-Hackers-Upload-Defacement-Page-to-Website-of-Indian-Railways-421261.shtml

http://hackread.com/pakistani-team-madleets-hacks-indian-railway/?utm_term=OSINT&utm_source=twitterfeed&utm_medium=twitter

**Comment by Usaar** [comment]
Submitted.
