### ISSUE TITLE
Oyo leaves customer data exposed due to a security flaw

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#14277]
https://tech.economictimes.indiatimes.com/news/startups/oyo-leaves-customer-data-exposed-due-to-a-security-flaw/71394350

**Comment by swidup** [comment]
https://inc42.com/buzz/oyo-security-flaw-leaves-customer-data-phone-numbers-unprotected/

**Comment by planglois925** [comment]
Vulnerability was demonstrated but no indication that data was accessed
