### ISSUE TITLE
Nunavut Government’s IT System Struck by Ransomware

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#14439]
https://securityboulevard.com/2019/11/nunavut-governments-it-system-struck-by-ransomware-attack/

**Comment by swidup** [comment]
https://www.zdnet.com/article/canadian-nunavut-government-systems-crippled-by-ransomware/

https://www.theregister.co.uk/2019/11/04/ransomware_freezes_nunavut_canada/

**Comment by gdbassett** [comment]
https://nunatsiaq.com/stories/article/government-of-nunavut-says-its-computer-backups-are-ok-despite-ransomware-attack/

https://nunatsiaq.com/stories/article/government-of-nunavut-slowly-rebuilds-computer-network-following-ransomware-attack/

**Comment by gdbassett** [comment]
https://www.facebook.com/GovofNunavut/posts/2533848170026447
https://twitter.com/JSavikataaq/status/1190727062690115586
