### ISSUE TITLE
Transcription Site Rev Leaves Customer Data Out in the Open

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#14521]
https://onezero.medium.com/rev-a-transcription-service-used-by-police-and-journalists-leaves-customer-data-out-in-the-open-81fff9f16669

**Comment by gdbassett** [comment]
Invalid as the only people with access to the data were alleged victim contractors under privacy agreement.  While not good practice to exposed data to all company contractors and employees, it is not necessarily a breach.
