### ISSUE TITLE
Cyberattack exposes information of 15 million LifeLabs customers in B.C. and Ontario

### ISSUE THREAD

**Issue by nschonni** [vz-risk/VCDB#14704]
https://www.cbc.ca/news/canada/british-columbia/lifelabs-cyberattack-15-million-1.5399577

https://www.bleepingcomputer.com/news/security/lifelabs-data-breach-exposes-personal-info-of-15-million-customers/

**Comment by swidup** [comment]
https://globalnews.ca/news/6308439/lifelabs-data-breach/

https://finance.yahoo.com/news/lifelabs-releases-open-letter-customers-following-cyber-attack-182000554.html

**Comment by swidup** [comment]
https://leaderpost.com/technology/tech-news/six-months-after-cyberattack-lifelabs-introduces-ciso-and-new-security-policies/wcm/fd5f462c-9e40-49f8-9e99-a74629b24dba/

**Comment by swidup** [comment]
https://www.thestar.com/news/lifelabs-patients-affected-by-2019-data-breach-may-be-eligible-for-up-to-150-heres/article_395241e4-978f-11ee-8855-9bff40d8c75f.html
