### ISSUE TITLE
loyaltybuild data breach may be the biggest in Western Europe

### ISSUE THREAD

**Issue by blackfist** [vz-risk/VCDB#1478]
Still looking for details about what happened and when it happened.

http://www.loyaltybuild.com/about-us/about-loyaltybuild.html
http://www.retail-systems.com/rs/Loyaltybuild_Data_Breach.php
http://www.dataprotection.ie/docs/12-11-13-Press-Release-Data-Breach-at-Loyaltybuild/1365.htm
https://www.net-security.org/secworld.php?id=15939
http://www.irishtimes.com/news/crime-and-law/breach-one-of-biggest-in-europe-in-last-three-years-1.1593370?page=1

**Comment by nicolasvillatte** [comment]
Merged with Issue #763.
