### ISSUE TITLE
Las Vegas Hacked: Sin City Hit

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#14827]
https://www.cbronline.com/cybersecurity/breaches/las-vegas-hacked/

**Comment by swidup** [comment]
https://news3lv.com/news/local/las-vegas-data-breach-comes-amid-homeland-security-warning-on-iranian-cyber-threat

**Comment by gdbassett** [comment]
https://www.zdnet.com/article/city-of-las-vegas-said-it-successfully-avoided-devastating-cyber-attack/
