### ISSUE TITLE
 Confidential details of entire WA Police Force accessed in 'startling' audit breach, CCC finds

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#15515]
https://www.msn.com/en-au/news/australia/confidential-details-of-entire-wa-police-force-accessed-in-startling-audit-breach-ccc-finds/ar-BB134cK4

**Comment by planglois925** [comment]
https://www.abc.net.au/news/2020-04-23/ccc-report-reveals-auditor-accessed-wa-police-officer-details/12176944
