### ISSUE TITLE
Brazil's Biggest Cosmetic Brand Natura Exposes Personal Details of Its Users

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#15637]
https://thehackernews.com/2020/05/natura-data-breach.html

**Comment by swidup** [comment]
https://www.hackread.com/brazis-cosmetic-giant-natura-leaked-192m-records/

**Comment by swidup** [comment]
https://secalerts.co/article/192-million-records-compromised-in-cosmetic-giants-data-leak/aaffcaf9

**Comment by gdbassett** [comment]
https://tecnoblog.net/340039/natura-expoe-dados-pessoais-de-250-mil-clientes-em-servidores-desprotegidos/
