### ISSUE TITLE
Cyber ​​attack on the San Raffaele hospital in Milan

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#15664]
https://www.databreaches.net/cyber-%E2%80%8B%E2%80%8Battack-on-the-san-raffaele-hospital-in-milan/

https://www.suspectfile.com/attacco-informatico-allospedale-san-raffaele-di-milano/

**Comment by dhylender** [comment]
first link is contradictory and confusing. Sec researcher says there was a breach, the hospital authorities says it was a non-event. the second link is broken. closing without coding.
