### ISSUE TITLE
E-Learning Platforms Continue to Suffer Data Breaches; 1 Mn Records Exposed

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#15935]
https://cisomag.eccouncil.org/data-breaches-on-e-learning-platforms/

Escola Digital, a Brazil-based online learning platform, suffered a data leak that exposed over 75,000 private records (15MB) of students and teachers.
South Africa-based online learning platform MyTopDog lost over 800,000 students’ personal records (40-50MB).
Okoo, a Kazakhstan-based online course portal, lost around 7,200 records (418MB) that held students’ personally identifiable information and administrative data.
The U.S.-based online education platform Square Panda lost around 15,000 personal records (1MB) of parents and teachers.
S.-based virtual learning platform Playground Sessions’ data leak exposed nearly 4,100 user records (1.2MB).

**Comment by swidup** [comment]
https://cisomag.eccouncil.org/data-breaches-on-e-learning-platforms/

**Comment by planglois925** [comment]
15935-1: Escola Digital, a Brazil-based online learning platform, suffered a data leak that exposed over 75,000 private records (15MB) of students and teachers. 
15935-2: South Africa-based online learning platform MyTopDog lost over 800,000 students’ personal records (40-50MB).
15935-3: Okoo, a Kazakhstan-based online course portal, lost around 7,200 records (418MB) that held students’ personally identifiable information and administrative data
15935-4: The U.S.-based online education platform Square Panda lost around 15,000 personal records (1MB) of parents and teachers.

15935-5: U.S.-based virtual learning platform Playground Sessions’ data leak exposed nearly 4,100 user records (1.2MB).
