### ISSUE TITLE
9 GitHub Repositories Found Leaking Health Data from Over 150K Patients

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#16118]
https://healthitsecurity.com/news/9-github-repositories-found-leaking-health-data-from-over-150k-patients

Xybion, a software, services and consulting company  
MedPro, a medical billing and management services vendor  
Sumana Ketha, M.D., who owns a range domains and entities in Texas, including Texas Physician House Calls  
VirMedica, e-access technology solutions vendor  
MaineCare, state and federally-funded healthcare provider  
Waystar, a revenue cycle management solutions vendor  
Shields Healthcare Group, a New England-based MRI provider  
Acc-q Data Network, a medical billings service provider

**Comment by planglois925** [comment]
16118-1: Xybion
16118-2: MedPro 
16118-3 : Texas Physician House Calls
16118-4: VirMedica
16118-5: MaineCare
16118-6: Waystar
16118-7: Shields Healthcare Group
16118-8: Acc-q Data Network
