### ISSUE TITLE
Free photos, graphics site Freepik discloses data breach impacting 8.3m users

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#16139]
https://www.zdnet.com/article/free-photos-graphics-site-freepik-discloses-data-breach-impacting-8-3m-users/

**Comment by swidup** [comment]
https://securityboulevard.com/2020/08/freepik-company-discloses-data-breach-affecting-more-than-8-million-users/

**Comment by alexcpsec** [comment]
ccf41c34-9ee6-4125-a62b-0d2a99389ea1
