### ISSUE TITLE
Builder's apprentice watched heart op at hospital - Capital & Coast DHB

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#16401]
https://www.odt.co.nz/star-news/star-national/builders-apprentice-watched-heart-op-hospital

**Comment by swidup** [comment]
https://www.ccdhb.org.nz/news-publications/news-and-media-releases/2020-10-10-investigation-concluded-into-theatres-security-breach/

**Comment by gdbassett** [comment]
though the computerized building security system was bypassed, it was similar to simply stealing a key to bypass a lock.  No other computers were involved, just a breach of patient privacy.  Therefore closing as invalid.
