### ISSUE TITLE
MMO game Street Mobster leaking data of 1.9 million users due to critical vulnerability - BigMage Studios

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#16456]
https://europeangaming.eu/portal/latest-news/2020/10/22/79947/mmo-game-street-mobster-leaking-data-of-1-9-million-users-due-to-critical-vulnerability/

**Comment by alexcpsec** [comment]
a38196e0-d15b-4a87-a6b9-9ccc99a19d9d
