### ISSUE TITLE
Data breach discovered at the Achievement Center of LECOM Health

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#17529]
https://www.yourerie.com/news/local-news/data-breach-discovered-at-the-achievement-center-of-lecom-health/

**Comment by swidup** [comment]
https://www.erienewsnow.com/story/43797546/personal-data-exposed-in-achievement-center-data-breach

**Comment by dhylender** [comment]
this is a duplicate. I coded it yesterday. closing it out.
