### ISSUE TITLE
A bug in a medical startup’s website put thousands of COVID-19 test results at risk - Total Testing Solutions

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#18031]
https://techcrunch.com/2021/08/17/a-simple-website-bug-put-thousands-of-covid-19-test-results-at-risk/

**Comment by planglois925** [comment]
The article doesn't state that any other customer's data was taken, so it seems just like a vulnerability disclosure without a breach, which is considered invalid as an incident.
