### ISSUE TITLE
Update to Riot Games (League of Legends) incident

### ISSUE THREAD

**Issue by krmaxwell** [vz-risk/VCDB#1811]
http://www.dailydot.com/esports/league-of-legends-hacker-arrest/

**Comment by nicolasvillatte** [comment]
https://web.archive.org/web/20140322061000/http://www.dailydot.com/esports/league-of-legends-hacker-arrest/

**Comment by nicolasvillatte** [comment]
https://web.archive.org/web/20150204062054/http://www.dailydot.com/esports/jason-shane-duffy-league-of-legends-hacks/
