### ISSUE TITLE
SuperCare Health California Data Breach Notice Issued

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#18648]
https://www.legalscoops.com/supercare-health-california-data-breach-notice-issued/

**Comment by swidup** [comment]
https://www.hipaajournal.com/supercare-health-sued-over-318000-record-data-breach/

**Comment by gdbassett** [comment]
no actions noted

**Comment by swidup** [comment]
### Additional Source Found

**Source:** https://www.ktmc.com/supercare-health-data-breach-investigation-2022/
**Headline:** SuperCare Health Data Breach Investigation 2022 | Kessler Topaz
**Data types:** PII, PHI, Financial
**Record count:** 300,000
**Alert keywords:** security breach -"18 and abused" -essay -dissertation -thesis -FNAF -"Five Nights at Freddy's"

*Confidence: 95% | Added by vcdb-pipeline*
