### ISSUE TITLE
LastPass Password Manager Admits it Had a Data Breach — Should You Change Your Passwords?

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#18946]
https://www.itechpost.com/articles/113308/20220825/lastpass-password-manager-data-breach.htm

**Comment by swidup** [comment]
https://www.securityweek.com/lastpass-says-source-code-stolen-data-breach

**Comment by gdbassett** [comment]
https://blog.lastpass.com/2022/08/notice-of-recent-security-incident/
