### ISSUE TITLE
IRS mistakenly publishes 112,000 taxpayer records for the second time - Accenture

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#19239]
https://www.itpro.co.uk/security/data-breaches/369747/irs-mistakenly-publishes-112000-taxpayer-records-for-the-second-time

**Comment by etgifford** [comment]
https://news.bloombergtax.com/daily-tax-report/irs-accidentally-releases-112-000-taxpayers-private-data-again

**Comment by etgifford** [comment]
IRS, HQ: Washington DC, NAICS 92921, Emp: 84,553 (tax collection, finance). 112000 taxpayer records (Form 990-T for individual and tax-exempt organizations) were mistakenly published Nov 23, 2022. Dec 1, 2022 a third-party researcher notified the IRS and the records were removed. Data contained names and  business contact information. Tax-exempt groups/organization forms are public, but forms filed by individuals are kept private. IRS gave corrected data to Accenture Nov 23, 2022 , but Accenture did not purge the old files from the system.
