### ISSUE TITLE
U.S. airline accidentally exposes ‘No Fly List’ on unsecured server - CommuteAir, TSA

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#19385]
https://www.dailydot.com/debug/no-fly-list-us-tsa-unprotected-server-commuteair/

**Comment by swidup** [comment]
https://www.scmagazine.com/brief/privacy/over-1-5-million-records-exposed-by-compromised-tsa-no-fly-list

**Comment by etgifford** [comment]
https://www.cnn.com/2023/01/20/politics/tsa-no-fly-list-data-cybersecurity/index.html
https://apps.web.maine.gov/online/aeviewer/ME/40/07918552-e40b-46b5-ba6c-367432d15491.shtml
