### ISSUE TITLE
Planet Ice hacked! 240,000 skating fans' details stolen

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#19427]
https://www.bitdefender.com/blog/hotforsecurity/planet-ice-hacked-240-000-skating-fans-details-stolen/

**Comment by etgifford** [comment]
https://www.bbc.co.uk/news/uk-england-bristol-64388071#:~:text=An%20email%20sent%20to%20customers,passwords%20used%20for%20Planet%20Ice.
https://monitor.firefox.com/breach-details/PlanetIce

**Comment by etgifford** [comment]
Planet Ice, HQ: Gillingham, England, EMP: 84, NAICS: 71399 (amusement and recreation) which operates 14 ice rinks up and down the UK, has revealed that criminal hackers managed to break into its systems on Jan 14, 2023 and steal the personal details of over 240,488 customers: date of birth, names and genders of children having parties, email address, IP addresses, passwords, phone numbers, addresses, and purchases.

**Comment by alexcpsec** [comment]
This one is covered by our ICO UK dataset. No need to code.
