### ISSUE TITLE
110,000 More Users Affected In 'LG Uplus' Data Breach: Report - LG Uplus

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#19434]
https://www.news18.com/news/tech/110000-more-users-affected-in-lg-uplus-data-breach-report-6999787.html

**Comment by swidup** [comment]
https://www.koreatimes.co.kr/www/tech/2023/02/419_345585.html

**Comment by etgifford** [comment]
https://en.yna.co.kr/view/AEN20230712008000320
https://www.pipc.go.kr/np/cop/bbs/selectBoardArticle.do?bbsId=BS074&mCode=C020010000&nttId=9030#LINK
https://koreajoongangdaily.joins.com/2023/02/16/business/tech/Korea-LG-U-Data-leakage/20230216185735270.html
https://www.databreaches.net/kr-pipc-sanctions-lg-u-telecom-imposes-administrative-penalty-of-5-3-million-for-breach-along-with-corrective-orders/

**Comment by etgifford** [comment]
LG Uplus (LG U+), HQ: Seoul, South Korea, EMP: 10262, NAICS: 517112 (wireless telephone, telecommunications) Jan 10, 2023 disclosed on its website a data breach of 297,117 customers: name, birthday, address, and phone number. On Jan. 02, 2023 a group claiming that it hacked the LG U+ attempted to sell the information on an online forum. The investigation into the breach discovered that during the development of the Customer Authentication System (CAS), webshell inspection, webshell detection, and blocking policies were not applied, leaving it vulnerable allowing a webshell to be uploaded in June 2018. The webshell was discovered and deleted January 23, 2023. The investigation also discovered basic security equipment such as firewalls, intrusion prevention system (IPS), and web firewall were not installed or, if installed, security policies were not properly applied. NOTE: Following the information security breach, the company underwent a total of five DDoS attacks on Jan29, 2023 and Feb 04, 2023, causing internet service failures.

**Comment by alexcpsec** [comment]
Reviewed.
