### ISSUE TITLE
Instant Checkmate, TruthFinder Data Breach: 20M Accounts Leaked - PeopleConnect

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#19440]
https://www.hackread.com/instant-checkmate-truthfinder-data-breach/

**Comment by swidup** [comment]
https://www.truthfinder.com/security-incident-alert/ on their site.  The same is posted for the other brand.

**Comment by swidup** [comment]
https://www.bleepingcomputer.com/news/security/truthfinder-instant-checkmate-confirm-data-breach-affecting-20m-customers/

**Comment by etgifford** [comment]
PeopleConnect, HQ: San Diego, CA: EMP: 74, NAICS: 56199 (technology, information and internet, information and document management, business services). On Jan 21, 2023, unidentified hackers leaked a 2019 backup database of two of their subscription-based background check services: TruthFinder (online service that enables users to search for information about people, businesses, and phone numbers) and Instant Checkmate (online tool that provides users with access to public records) on Breach Forum. The databases (2.9 GB CSV files. Upon extraction the data set was 7 GB) contained 20,211,007 customer accounts created from 2011 – 2019 before the backup was created on Apr 16, 2019. Data: names, phone numbers, email addresses, password hashes, and password reset tokens. The data came from a cloud storage location maintained and used by a former service provider. The owner of the Breached forum where the data was posted also confirmed the data was exfiltrated from an exposed database backup found by a forum member.

**Comment by alexcpsec** [comment]
Reviewed.
