### ISSUE TITLE
GTA Modder's October 2022 Data Breach Exposed Over 100,000 Emails

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#19524]
https://gamerant.com/gta-modder-october-2022-data-breach-exposed-emails/

**Comment by etgifford** [comment]
https://twitter.com/FalconFeedsio/status/1584795069260869632
https://www.redpacketsecurity.com/realdudesinc-101-543-breached-accounts/

**Comment by etgifford** [comment]
RealDudesInc, HQ: Houston, TX, EMP: 6, NAIC: 999990 (unclassified establishment). On Oct 21, 2022 the GTA Mod Menu Provider and reseller for Grand Theft Auto was hacked through the GTA Modder (user modification of video games in the open world sandbox GTA series are popular in the PC gaming community). User 101,543 accounts were affected: Usernames, bcrypt password hashes, and emails. Oct 24, 2022, the database was uploaded to The Hacker’s Forum.

**Comment by etgifford** [comment]
NAICS clarification: 518210 (Data Processing, Hosting, and Related Services)

**Comment by alexcpsec** [comment]
There are no details on how the breach happened. Not eligible.
