### ISSUE TITLE
The Good Guys customers' personal data stolen in cyberattack on third-party supplier - Pegasus Group Australia Pty Ltd 

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#19540]
https://www.9news.com.au/national/the-good-guys-customers-personal-data-stolen-in-thirdparty-cyber-attack/9c9c0574-0744-4de7-a643-f905afa9d780

https://www.abc.net.au/news/2023-02-23/good-guys-customers-possibly-affected-by-my-rewards-data-breach/102014976

"Up to 1.5 million customers"

**Comment by etgifford** [comment]
https://www.channelnews.com.au/1-85m-good-guys-customers-impacted-by-data-breach/

**Comment by etgifford** [comment]
My Rewards (now known as Pegasus Group Australia Pty LTD), HQ: Australia, EMP: 25, NAICS: 541608 (promoting and developing loyalty and reward programs for companies) previously ran “The Good Guy’s” reward service for “concierge members” for The Good Guys, HQ: Australia, EMP: 1765, NAICS: 4431 (customer electronics and computer retail, retail). A hack of Pegasus in Aug 2021 revealed details of 1,850,000 Concierge members: name, address, phone number, email address, encrypted passwords, and date of birth. The Good Guys were notified about the breach in Feb 2023.

**Comment by alexcpsec** [comment]
No details on how the breach took place. Not eligible.
