### ISSUE TITLE
Minneapolis Public Schools still investigating what caused ‘encryption event’

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#19556]
https://therecord.media/minneapolis-public-schools-still-investigating-what-caused-encryption-event/

**Comment by swidup** [comment]
https://www.shsoutherner.net/features/2023/03/12/mps-falls-victim-to-ransomware-attack-sensitive-information-threatened-to-be-released-unless-1-million-ransom-is-paid/

**Comment by swidup** [comment]
https://www.kare11.com/article/news/local/minneapolis-public-schools-confirms-hackers-released-personal-data/89-8e682442-2da4-434f-8e03-19f5d08009fe

**Comment by swidup** [comment]
https://www.nbcnews.com/tech/security/students-psychological-reports-abuse-allegations-leaked-ransomware-hac-rcna79414 data types leaked

**Comment by swidup** [comment]
https://www.campussafetymagazine.com/safety/over-189000-files-leaked-minneapolis-public-schools-data-breach/ 189k

**Comment by swidup** [comment]
https://therecord.media/minneapolis-schools-say-data-breach-affected-100000

**Comment by etgifford** [comment]
Official Notification to the State of Main ehttps://apps.web.maine.gov/online/aeviewer/ME/40/839d2bfc-d5bd-45ce-8ab0-69902280a2ad.shtml
Notice of Data Event to the State of Maine https://apps.web.maine.gov/online/aeviewer/ME/40/839d2bfc-d5bd-45ce-8ab0-69902280a2ad/4ff042a2-bb81-4902-a58c-1eb3e452ea59/document.html

**Comment by etgifford** [comment]
Minneapolis Public Schools (MPS), HQ: Minneapolis, MN, EMP: 5506, NAICS: 923110 (public education) announced Mar 01, 2023 it had experienced an “encryption event” on Feb 18, 2023. Immediate steps were taken to secure the MPS environment. Investigation showed the actor had access between Feb 06 - 18, 2023. A $1 million ransom has been placed on the personal data of 105,617 people recently stolen from Minneapolis Public Schools by the ransomware group Medusa on their dark web website. The deadline for responding was March 17, 2023. Leaked data (going as far back as 1995): payroll, health information, union grievances, civil rights investigations, personal phone numbers, home addresses, and personal email addresses of staff, students, and parents, teacher employment information and salaries, grant information, contracts, names of student sexual assault victims, school bank account deposit records, student IDs including photos. MPS restored systems and did not pay the ransom. MPS started notifying impacted individuals Apr 07, 2023. Investigation was completed Jul 24, 2023. Impacted individuals are offered 24 months of credit monitoring through Experian.

**Comment by alexcpsec** [comment]
Reviewed.
