### ISSUE TITLE
Personal data of 254K Medicare beneficiaries at risk after breach - ASRC Federal Data Solutions

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#19622]
https://www.fairfieldsuntimes.com/news/national/personal-data-of-254k-medicare-beneficiaries-at-risk-after-breach/article_7a45b15b-24fd-5449-81c5-292719309090.html

**Comment by etgifford** [comment]
Above URL for fairfieldsuntimes.com is 404.

Good URLs:
https://potomacofficersclub.com/news/cms-project-subcontractor-suffers-cyber-attack/
https://www.cms.gov/newsroom/press-releases/cms-responding-data-breach-subcontractor

**Comment by etgifford** [comment]
https://www.healthcareitnews.com/news/cms-subcontractor-hit-ransomware

**Comment by etgifford** [comment]
Summary: Healthcare Management Solutions, LLC (HMS), HQ: West Virginia, NAICS: 56561, 130 employees (Information Technology, Federal Oversight for Healthcare Facility Compliance, Data Collection, Analysis, and Reporting, Secure Web-based Portals, IV&V, Helpdesks, Healthcare Delivery Analysis, Software Development, and Medical Record Review and Analysis)., is a subcontractor to ASRC Federal Data Solutions, LLC project for the Centers for Medicare and Medicaid Services (CMS). HMS suffered a ransomware attack that affected 254,000 Medicare beneficiaries: Name, Address, Date of Birth, Phone Number, Medicare Beneficiary Identifier, Banking information including routing and account numbers, Medicare entitlement/enrollment/premium information. Social Security Numbers. October 8, 2022 HMS had a ransomware attack. On October 9, 2022 CMS was notified. October 18, 2022 CMS determined PII and PHI was compromised. December 1, 2022 CMS determined data breach was a "major incident".

**Comment by alexcpsec** [comment]
Reviewed.
