### ISSUE TITLE
Digital marketing agency suffered breach of 105,008 users due to hacking

### ISSUE THREAD

**Issue by jaybobo** [vz-risk/VCDB#19667]
https://apps.web.maine.gov/online/aeviewer/ME/40/445022f0-f986-4520-be8b-983f984f569e.shtml

Identified by BreachSiren.

**Comment by etgifford** [comment]
Svanaco, Inc, ( HQ in Illinois, doing business as americaneagle.com. Has 515 employees doing web design, development, integration, hosting, digital marketing, maintaining websites. NAICS 51516) . On Nov 16, 2022, Americaneagle.com was alerted to unusual activity for online store baretta.com/en-us. On March 1, 2023 americaneagle.com received confirmation from the investigators it hired, that the breach occured July 13, 2022 and payment card info was accessed on 105008 accounts between July 13, 2022 and Dec 5, 2022. Info was name, home address, phone number, payment card numbers, expiration dates, and security codes.

**Comment by alexcpsec** [comment]
Reviewed.
