### ISSUE TITLE
Onix Group, LLC Announces Data Breach Following Ransomware Attack

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#19804]
https://www.jdsupra.com/legalnews/onix-group-llc-announces-data-breach-4296104/

**Comment by swidup** [comment]
https://www.hipaajournal.com/phi-of-320000-patients-affected-by-onix-group-ransomware-attack/ 320,000 records.

**Comment by etgifford** [comment]
9b9fb064-8635-4811-952a-e6c77a457c2f
