### ISSUE TITLE
Citi Trends, Inc. suffers a breach of 285 records due to External system breach (hacking)

### ISSUE THREAD

**Issue by jaybobo** [vz-risk/VCDB#19861]
-> Date: 2023-06-23 00:00:00
    -> Name: Citi Trends, Inc.
    -> Source: https://apps.web.maine.gov/online/aeviewer/ME/40/07c5c0b1-c0bc-4579-bfb6-697b4bfd4e4b.shtml
    -> Persons Affected: 285
    -> Description: External system breach (hacking)
    -> Information Acquired: Social Security Number

    Created by: BreachSiren Bot

    For questions contact: (info[at]breachsiren[dot]com)

**Comment by swidup** [comment]
https://www.jdsupra.com/legalnews/citi-trends-inc-announces-data-breach-7838536/
