### ISSUE TITLE
HCA sends notice to patients informing them of data breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#19904]
https://www.healthcarefinancenews.com/news/hca-sends-notice-patients-informing-them-data-breach

https://www.beckershospitalreview.com/cybersecurity/hca-notifies-11-million-patients-affected-in-data-breach.html  11 million affected

**Comment by alexcpsec** [comment]
5c6ec276-9f33-42df-96bc-a30d2462b1f9

**Comment by alexcpsec** [comment]
Ended up doing Error -> Hacking for this one. Multiple actors.
