### ISSUE TITLE
Bookstore Chain Dymocks Discloses Data Breach Possibly Impacting 800k Customers

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#19938]
https://www.securityweek.com/bookstore-chain-dymocks-discloses-data-breach-possibly-impacting-800k-customers/

**Comment by swidup** [comment]
https://www.scmagazine.com/brief/dymocks-booksellers-data-breach-hits-over-836k

**Comment by swidup** [comment]
https://ia.acs.org.au/article/2023/1-2-million-customers-caught-up-in-dymocks-breach.html

**Comment by dhylender** [comment]
This was a partner breach but (I am guessing due to Australian law) the partner is not named. Need more details.
