### ISSUE TITLE
Drug Free Workplaces USA Notifies Over 37,000 Individuals of Data Breach That Leaked Their SSNs

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20046]
https://www.jdsupra.com/legalnews/drug-free-workplaces-usa-notifies-over-5207251/

**Comment by etgifford** [comment]
https://www.maine.gov/agviewer/content/ag/985235c7-cb95-4be2-8792-a1252b4f8318/da0cbf61-89ee-447c-baca-abb1b6129b27.shtml

**Comment by etgifford** [comment]
JSON f974132f-e6f6-44ac-86f2-93b8ab11d9a2, Drug Free Workplaces USA, HQ: Pensacola, FL, EMP: 25, NAICS: 541380 (Testing Laboratories). March 29, 2023 data breach of two email accounts discovered May 04, 2023. Investigation ended Sept 29, 2024 affecting 37705 customers. Data exfiltrated: names and SSNs. Letters were sent to those affected Oct 27, 2023. 12-month ID theft protection through IDX. Two employee email accounts were compromised (phishing). Class Action lawsuit filed Oct 2023.
