### ISSUE TITLE
81K people's sensitive info feared stolen from Hilb after email inboxes ransacked

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20057]
https://www.theregister.com/2023/11/03/hilb_data_leak/

https://apps.web.maine.gov/online/aeviewer/ME/40/efcbb550-4093-4bdf-95a0-ecd868472099.shtml

**Comment by swidup** [comment]
https://www.jdsupra.com/legalnews/the-hilb-group-announces-data-breach-4948605/

**Comment by etgifford** [comment]
JSON 061fc5cb-a2b4-4d88-9c79-b429f970fe8a, The Hilb Group, HQ: Richmond, VA, EMP: 884, NAICS: 524210 (Insurance Agencies and Brokerages). An employee of The Hilb Group clicked on a phish, which lead to the data leak of the information of 81539 customers. Data stolen: financial account number and credit card numbers including the security code, access code, password, or PIN, SSNs, Passwords, PINs. Around Jan 10, 2023, Hilb discovered suspicious activity related to email accounts. Breach occurred Dec 01, 2022 and was discovered Oct 09, 2023. The investigation was completed Jul 28, 2023. Letters were sent to customers notifying them on Nov 02, 2023. 12 months of ID theft protection through TransUnion was offered.
