### ISSUE TITLE
City of St. John's warns of phishing scam following privacy breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20060]
https://www.cbc.ca/news/canada/newfoundland-labrador/st-johns-phishing-scam-1.7016697

**Comment by etgifford** [comment]
https://www.stjohns.ca/en/news/residents-advised-of-potential-phishing-scam-related-to-privacy-breach.aspx

**Comment by etgifford** [comment]
JSON bf4d7f8a-035f-4695-a066-f8e80912f2a1, City of St Johns, HQ: St Johns, Newfoundland and Labrador, EMP: 1505, NAICS: 921000 (Executive, Legislative, and Other General Government Support). On Oct 31, 2023, an employee clicked on a phish resulting in a breach involving 219 residents. An employee sent an accounts receivable report to someone posing as another city employee. Data taken: names, account numbers, amounts owed. The City became aware of the breach on Nov 2, 2023. Residents impacted were notified Nov 2, 2023
