### ISSUE TITLE
Data of 171,871 Deer Oaks Behavioral Health clients and employees dumped by ransomware group

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20074]
https://www.databreaches.net/data-of-171871-deer-oaks-behavioral-health-clients-and-employees-dumped-by-ransomware-group/

**Comment by etgifford** [comment]
f6d9b66f-7f79-423a-ace8-1218ef248a33.JSON

**Comment by swidup** [comment]
https://www.govinfosecurity.com/mental-health-provider-fined-225k-for-lack-risk-analysis-a-28916?rf=2025-07-09_ENEWS_SUB_GIS__Slot9_ART28916 fined by HHS
