### ISSUE TITLE
Data leak hits 665,000 MBS rewards programme members - Marina Bay Sands

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20077]
https://www.straitstimes.com/tech/data-leak-hits-665000-mbs-rewards-programme-members

**Comment by swidup** [comment]
https://www.bleepingcomputer.com/news/security/marina-bay-sands-discloses-data-breach-impacting-665-000-customers/

**Comment by etgifford** [comment]
1b9d94f9-6966-4866-865d-e0603f2c6976.JSON
