### ISSUE TITLE
Butler County Investigating Cyber Security Incident

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20095]
https://butlerradio.com/county-investigating-cyber-security-incident/

**Comment by swidup** [comment]
https://www.wpxi.com/news/local/personal-information-impacted-breach-computer-network-butler-county-says/ZFCC5N37IFBOZP3UI72NDT5CZY/

https://www.butlereagle.com/20231108/personal-information-breached-in-data-security-incident-county-says/

**Comment by swidup** [comment]
https://www.wtae.com/article/butler-county-network-hack/46893490 confirmed data types stolen

**Comment by etgifford** [comment]
https://butlercountypa.gov/DocumentCenter/View/7715/Notice_of_Data_Security_Incident_20240221-PDF?bidId=
https://www.cbsnews.com/pittsburgh/news/butler-county-computer-system-hackers-personal-information-exposed/

**Comment by etgifford** [comment]
JSON: e3bbab6f-92ce-416c-b2c9-b54e83ec57d4 ,Butler County, PA , HQ: Pittsburg, PA, EMP: 1239, NAICS: 921140 (Executive and Legislative Offices, Combined). On October 2, 2023, federal law enforcement alerted Butler County to suspicious activity. On Oct 30, 2023, it was discovered the data of 6748 people had been breached. Data included the following: name, Social Security number, driver’s license number, state identification number, individual taxpayer identification number, and passport number. The county completed the review of the incident Jan 22, 2024. Notifications started being mailed out Feb 21, 2024.Complementary credit monitoring for one year.
