### ISSUE TITLE
Cyber attack hits council computer systems at Comhairle nan Eilean Siar

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20099]
https://www.bbc.com/news/uk-scotland-highlands-islands-67355465

**Comment by etgifford** [comment]
JSON fa6be9a4-4057-4940-aadb-7357833236cb Western Isles Local Authority: Comhairle nan Eilean Siar, Stornoway, Scotland, 326 employees, NAICS  921190 Other Government General Support. Nov 7, 2023 data on operational and backup servers cannot be accessed. Discovered when the website was reported to be offline. No evidence of data extraction. Affected phone systems, email, benefit payments, children and adult social care services, tax billing, and tax payments. Cost to recover: $6245000 estimate (500K Pounds)

**Comment by alexcpsec-vz** [comment]
Ransomware with no breach
