### ISSUE TITLE
Tri-City Healthcare halts emergency operations after ransomware attack

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20103]
https://www.nbcsandiego.com/news/local/tri-city-healthcare-halts-emergency-operations-after-ransomware-attack-source/3351170/

**Comment by etgifford** [comment]
https://www.kpbs.org/news/local/2023/12/11/ransomware-group-reportedly-posts-some-tri-city-medical-center-documents-to-dark-web
https://oag.ca.gov/system/files/2024-04-04%20-%20Tri-City%20-%20CA%20Regulatory%20Notification%20Letter.pdf

**Comment by etgifford** [comment]
JSON 6f5b6c22-41b6-42d4-a412-89a57690e217 Tri-City Healthcare, Oceanside, CA , 500 employees , NAICS 622110 (General Medical and Surgical Hospital),  Staff noticed a security breach (disrupted access to certain systems) around 7 AM, Nov 9, 2023. Investigation showed access to network around Nov 8, 2023. INC RANSOM claimed responsibility and posted records of 7143 people on the dark web: patient authorization forms, financial records, name, phone number, social security number. April 4, 2024 letters mailed to 7143 residents. 12 months identity protection. Undisclosed attack method.
