### ISSUE TITLE
Huber Heights hit by ransomware cyber attack

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20120]
https://www.daytondailynews.com/local/huber-heights-city-government-hit-by-ransomware-cyber-attack/4HAJD66AGJFTDDYSU4IQS3AJGY/

https://www.hhoh.org/CivicAlerts.aspx?AID=414

**Comment by swidup** [comment]
https://statescoop.com/ransomware-attacks-huber-heights-ohio/

**Comment by swidup** [comment]
https://statescoop.com/huber-heights-ohio-ransomware-attack-victims/

**Comment by etgifford** [comment]
https://www.govtech.com/security/extent-of-damage-in-huber-heights-cyber-attack-unknown

**Comment by etgifford** [comment]
JSON f7b500bf-5b35-4153-8b80-77aa281bd90f, City of Huber Heights, HQ: Huber Heights, OH, EMP: 180, NAICS: 921190 (Other General Government Support). Nov 12, 2023 “BlackSuit” conducted a ransomware attack exposing data of 5738 people: 198-gigabyte file was found on the dark web for auction. Data taken: name, address, date of birth, SSN, and bank account information. Attack was detected by Huber Heights Dispatch Center. One year credit monitoring is being given to 2038 customers. Reports from cybersecurity sources indicated that the attack might have affected critical departments, including tax, zoning, engineering, finance, human resources, and economic development.  Credential replay was mentioned by CEO of Secure Cyber Defense. The city approved an allocation of up to $350,000 in city funds to address the fallout. Various entities have been engaged to aid in the recovery process, including Secure Cyber Defense for on-site response, Coveware for negotiations with the threat actors, and Sylint for forensic investigation, among others.
