### ISSUE TITLE
Ransomware attack responsible for shuttering St. Lucie County Tax Collector's computer system

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20154]
https://www.wptv.com/news/treasure-coast/region-st-lucie-county/ransomware-attack-responsible-for-shuttering-st-lucie-county-tax-collectors-computer-system

**Comment by etgifford** [comment]
https://x.com/H4ckManac/status/1724313102542311462?s=20
https://www.tcpalm.com/story/news/local/st-lucie-county/2023/11/14/ransomware-group-claims-it-took-sensitive-information-but-did-it/71571855007/
https://www.tcslc.com/290/Data-Privacy-Event
https://www.comparitech.com/news/the-week-in-ransoware-april-12-2024/

**Comment by etgifford** [comment]
JSON 83b075e8-9be9-47c6-ac18-be50aa510b26, St Lucie County Tax Collector, HQ: Ft Pierce, FL, EMP: 82, NAICS: 921190 (Other General Government Support). On Oct 27, 2023 LSCTC became aware of unusual activity on the network.  Investigation showed access on Oct 16, 2023 after an employee clicked on a phish. ALPHV/BlackCat posted evidence on a data Leak site on Nov 13, 2024. Data taken of 25,202 customers: name, date of birth, SSN, driver’s license number, and passport number. Notice sent Feb 21, 2024 advising of the details of the hack and giving one year credit monitoring and ID theft restoration services from TransUnion.
