### ISSUE TITLE
Yamaha Motor confirms ransomware attack on Philippines subsidiary

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20160]
https://www.bleepingcomputer.com/news/security/yamaha-motor-confirms-ransomware-attack-on-philippines-subsidiary/

**Comment by swidup** [comment]
https://www.securityweek.com/yamaha-motor-confirms-data-breach-following-ransomware-attack/

**Comment by etgifford** [comment]
https://sectrio.com/blog/inc-ransom-breaches-yamaha/

**Comment by etgifford** [comment]
JSON 891bc09d-47a0-43df-a0c7-f3defadd90a7, Yamaha Motors Philippines, HQ: Calabarzon Philipines, EMP: 1000-5000, NAICS: 336991 (Motorcycle, Bicycle, and Parts Manufacturing). On Oct 25, 2023 detected a ransomware attack at its Philippine motorcycle manufacturing subsidiary. A single server was breached. Nov 16, 2023 the investigation found data theft of employee PII. INC Ransom gang added Yamaha Motors to its dark web leak site on Nov 15, 2023 publishing 37GB of data including employee ID info, backup files, corporate and sales information.
