### ISSUE TITLE
Cyber criminals demand £600,000 ransom for stolen British Library data

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20171]
https://www.aol.com/cyber-criminals-demand-600-000-110625722.html

**Comment by swidup** [comment]
https://www.theguardian.com/technology/2023/nov/22/personal-data-stolen-in-british-library-cyber-attack-appears-for-sale-online

**Comment by etgifford** [comment]
https://blogs.bl.uk/living-knowledge/2024/03/learning-lessons-from-the-cyber-attack.html
https://www.bl.uk/home/british-library-cyber-incident-review-8-march-2024.pdf

**Comment by etgifford** [comment]
JSON 9180b47a-69f3-47c5-920f-70b9ca4d1af2, British Library, HQ: London, England, EMP: 1,300, NAICS: 519120 (Libraries and Archives). On Oct 26, 2023 the Library’s monitoring system automatically blocked suspicious activity at 00:21. A vulnerability scan was conducted and logs reviewed. The IT team did not malicious activity. On Oct 28, 2023, a member of the Library’s Technology Team was unable to access the library’s network. Forensics discovered that access into the network was on Oct 25, 2023 @ 23:29 with lateral movement seen @23:32. Exfiltration of approximately 600GB or 500,000 documents, was seen on Oct 28, 2023 @01:30, comprising 22 databases. Finance, Technology, and People teams were targeted, exfiltrating data of Library users and staff which included passport pictures and financial information. “Rhysida Group” took credit for the hack and demanded 20 Bitcoin (roughly £602,500) for the return of the stolen data. When the ransom was not paid, the data went up for auction on the dark web. Entry was determined to be a remote access Terminal Services server. Most likely through a successful phish. MFA was not a requirement for access.

**Comment by etgifford** [comment]
JSON 9180b47a-69f3-47c5-920f-70b9ca4d1af2, British Library, HQ: London, England, EMP: 1,300, NAICS: 519120 (Libraries and Archives). On Oct 26, 2023 the Library’s monitoring system automatically blocked suspicious activity at 00:21. A vulnerability scan was conducted and logs reviewed. The IT team did not malicious activity. On Oct 28, 2023, a member of the Library’s Technology Team was unable to access the library’s network. Forensics discovered that access into the network was on Oct 25, 2023 @ 23:29 with lateral movement seen https://github.com/23:32. Exfiltration of approximately 600GB or 500,000 documents, was seen on Oct 28, 2023 @01:30, comprising 22 databases. Finance, Technology, and People teams were targeted, exfiltrating data of Library users and staff which included passport pictures and financial information. “Rhysida Group” took credit for the hack and demanded 20 Bitcoin (roughly £602,500) for the return of the stolen data. When the ransom was not paid, the data went up for auction on the dark web. Entry was determined to be a remote access Terminal Services server. Most likely through a successful phish. MFA was not a requirement for access.
