### ISSUE TITLE
Prestige Care Data Breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20178]
https://www.hipaajournal.com/longhorn-imaging-center-cyberattack-affects-more-than-100000-patients/

"Prestige Care/Prestige Senior Living in Washington has recently announced that it fell victim to a cyberattack that was detected on or around September 7, 2023, that resulted in its network being infected with malware that prevented access to certain files. The investigation confirmed the unauthorized actor accessed files on its systems the same day the breach was detected.

The investigation and file review are ongoing, and the total number of individuals affected has yet to be determined, although Prestige has said the information of current and former employees and residents was compromised in the attack. The impacted information varies from individual to individual and may include names, Social Security numbers, dates of birth, medical information, and health insurance information. Notification letters will be sent to the affected individuals when the review is completed. To meet regulatory breach reporting requirements, the incident has been reported to the HHS’ Office for Civil Rights as affecting at least 501 individuals. The total will be updated when the review is completed.

The HIPAA Journal previously reported that the ALPHV/BlackCat ransomware group claimed responsibility for [the attack](https://www.hipaajournal.com/mclaren-health-care-ransomware-attack-may-affect-up-to-2-5-million-patients/) and had added Prestige to its data leak site and claimed to have stolen 260 GB of data. While the listing is still on the leak site, no data is currently downloadable."

**Comment by etgifford** [comment]
https://www.breachsense.com/breaches/prestige-care-data-breach/
https://www.thelyonfirm.com/blog/prestige-care-data-breach-investigation/

**Comment by etgifford** [comment]
JSON a6f9b39e-9ce9-49c3-a057-df2c29049192, Prestige Care, HQ: Vancouver, WA, EMP: 1,184, NAICS: 623110 (Nursing Care Facilities). On Sep 7. 2023 Prestige Care noticed they were a victim of ransomware when they could not access certain files in the system. An investigation completed Dec 18, 2023 confirmed the exfiltration of PII for 38,087 current and former patients: names, Social Security numbers, addresses, birthdates, medical record numbers, health insurance policy numbers and health information, including patient histories, conditions, diagnoses and treatments. ALPHV claimed responsibility on their website. Prestige Care began notifying those affected on Jan. 31, 2024. A lawsuit was filed Feb 16, 2024.
