### ISSUE TITLE
U.S. Drug Mart Files Notice of Data Breach Affecting Consumers’ Social Security Numbers  LinkedIn  Facebook  Twitter  Send

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20175]
https://www.jdsupra.com/legalnews/u-s-drug-mart-files-notice-of-data-3630484/

**Comment by etgifford** [comment]
JSON 13f6feae-487e-4daa-876b-bd2c759a323d, U. S. Drug Mart, HQ: Midlothian, TX, EMP: 59, NAICS: 446110 (Pharmacies and Drug Stores). On Sep 22, 2023, Micro Merchant Systems, Inc (MMS) (HQ: Syosset, NY, EMP: 103, NAICS: 511210 (Software Publishers)) notified USDM that they were victims of a data breach using stolen credentials between Aug 2 and Aug 5, 2023. MMS is a third-party vendor that hosts USDM’s patient data. Data of 13,016 customers were affected: patient names were given to USDM on Dec 1, 2023. Data included patient first and last names, date of birth, address, Social Security number, driver’s license, prescription information, and telephone number. December 14, 2023, USDM mailed notification letters to the individuals potentially impacted by this incident. On January 4, 2024, USDM mailed additional letters as MMS’ investigation continued. In those letters, USDM offered identity theft protection services and credit monitoring through ZeroFox for one year.
