### ISSUE TITLE
Warren General Hospital suffered data breach potentially affecting employees, patients

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20191]
https://www.yourerie.com/digital-first/digital-exclusive/warren-general-hospital-suffered-data-breach-potentially-affecting-employees-patients/

**Comment by etgifford** [comment]
https://ago.vermont.gov/sites/ago/files/documents/2023-11-17%20Warren%20General%20Hospital%20Data%20Breach%20Notice%20to%20Consumers.pdf

**Comment by etgifford** [comment]
JSON:, ff972691-84bf-485b-bc62-f4f1419f5cc6, Warren General Hospital, HQ: Warren, PA, EMP: 229, NAICS: 622110  (General Medical and Surgical Hospitals). Identified suspicious activity on their network Sept 24, 2023. Investigation shows network access Sept 15, 2023. Information downloaded on 168921 patients and employees was names, addresses, dates of birth, social security numbers, financial account information, payment card information, health insurance claims information, and medical information (diagnosis, meds, lab results). Data breach letters were mailed on Nov 09, 2023. WGH provided additional security training to staff.
