### ISSUE TITLE
Hackers steal IDF patient records from cyberattack on Israeli hospital - Ziv Medical Center

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20212]
https://www.jpost.com/israel-news/defense-news/article-775843

**Comment by etgifford** [comment]
https://therecord.media/ziv-hospital-israel-hackers-claim-to-leak-data 
https://www.jpost.com/israel-news/defense-news/article-775843 
https://www.darkreading.com/cyberattacks-data-breaches/israel-blames-iran-for-hospital-data-breach
https://www.i24news.tv/en/news/israel-at-war/1702886863-iran-hezbollah-behind-cyber-attack-on-israeli-hospital-according-to-investigation

**Comment by etgifford** [comment]
JSON 65f9812d-640d-4a41-910c-ac67eae3a7c1, Ziv Medical Center, HQ: Derech Harambam, Safed, Israel, EMP: 132, NAICS: 622110 (General Medical and Surgical Hospital). On Nov 27, 2024, hacker groups, “Malek Team” and “AGRIUS”, allegedly linked to Iranian Intelligence Ministry, and Hezbollah’s “Lebanese Cedar” cyber unit, stole 700,000 (500 gigabytes of data) medical records from a cyberattack, of those, 100,000 are IDF patient records. “Malek Team” posted screen shots of the data on their Telegram page. This was the third time Ziv fell victim to a cyberattack in four months. Data included patient’s personal and medical information such as diseases and prescribed drugs, and passport pictures. As a precautionary measure, Ziv implemented various new safeguards, temporarily restricting the sending and receiving of external emails. Certain computer services were also temporarily disconnected. The public is urged to exercise caution when receiving messages purporting to be from the hospital and to avoid opening any suspicious messages or clicking on any attached links.
NOTE: Mohammed Ali Marai was identified as the lead operator for the Hezbollah hacking group.

**Comment by alexcpsec-vz** [comment]
Added the possible fish as a Social action
