### ISSUE TITLE
Former Whittier Tech IT Specialist Pleads Guilty to Damaging School’s Computer Network

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20233]
https://www.bollyinside.com/news/technology/former-whittier-tech-it-specialist-pleads-guilty-to-damaging-schools-computer-network/

Conor LaHiff

**Comment by swidup** [comment]
https://www.bleepingcomputer.com/news/security/former-it-manager-pleads-guilty-to-attacking-high-school-network/

**Comment by etgifford** [comment]
JSON: fbef2a10-c880-4f8d-b7ee-ec277ff493a9, Whittier Regional Vocational Technical High School, HQ: Haverhill, MA, EMP: 120, NAICS: 611519 (Other Technical and Trade Schools). Former IT manager, Conor LaHiff, 30, admitted to committing a cyberattack against his former employer following the termination of his employment in June 13, 2023. LaHiff performed the following actions after the termination of his employment: Deleted 1,200 Apple IDs from the school's Apple School Manager account, Deactivated over 1,400 other Apple accounts, Attempted to disconnect Apple Class IDs, Course IDs, Location IDs, and Person IDs from the school's Apple School Manager account, Deactivated, administrative accounts, including accounts at security vendors., Disabled the school's private branch phone service. The announcement says that LaHiff's actions caused the school to incur at least $5,000 in direct financial losses. In December 2023, LaHiff pleaded guilty to one count of unauthorized damage to protected computers. He was sentenced by U.S. Chief District Court Judge F. Dennis Saylor IV to one month in prison and three years’ supervised release, the first 12 months to be served in home confinement.  He was also ordered to pay $34,110 in restitution.
