### ISSUE TITLE
STARGATE PLATFORM TARGETED IN PHISHING SCAM: OVER $50,000 STOLEN

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20231]
https://www.cryptopolitan.com/stargate-platform-targeted-in-phishing-scam/

https://crypto.news/stargate-used-voting-for-a-43k-phishing-attack/

**Comment by etgifford** [comment]
https://messari.io/report/understanding-layerzero

**Comment by etgifford** [comment]
JSON: bf8b4635-bc7d-436e-a425-cbfcdb594164, LayerZero Labs, HQ: Vancouver, British Columbia, Canada, EMP: 114, NAICS: 523210 (Securities and Commodity Exchanges). While blockchain networks are designed to be highly secure, they face the challenge of communicating with other networks while maintaining security requirements. This challenge has been exacerbated by the differing security models of various Layer-1s, Layer-2s, and modular networks. The LayerZero protocol was born from the need to securely communicate between networks. LayerZero allows communication between smart contracts operating on distinct networks: enables applications to send messages from a source network that will execute on a destination network. Stargate Finance (STG), is a bridge that uses LayerZero to communicate the movement of native assets across networks. On the Stargate Finance platform, an attacker bought 50,000 STG to gain access to create a voting proposal on the Snapshot site. On Dec 1, 2023 the attacker published an announcement about the launch of the first phase of gSTG token distribution. The advertisement contained a phishing link that led to a fraudulent website. More than 1,000 users followed it, the source notes. The incident came to light when the Discord Moderator for LayerZero, the underlying network for Stargate, flagged the fraudulent proposal. $63335 was stolen.
