### ISSUE TITLE
BSNL suffers data breach; sensitive info of users up for sale on dark web - Bharat Sanchar Nigam Ltd

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20288]
https://telecom.economictimes.indiatimes.com/news/industry/bsnl-suffers-data-breach-sensitive-info-of-users-up-for-sale-on-dark-web/106197459

**Comment by etgifford** [comment]
https://thecyberexpress.com/bsnl-data-breach-2/

**Comment by etgifford** [comment]
JSON: fa33d6fd-d184-43c4-8ab4-a2ca099da463, Bharat Sanchar Nigam Ltd (state run),  HQ: New Delhi, India, EMP: 56820, NAICS: 517210 (Wireless Telecommunications Carriers (except Satellite). Dec 03, 2023 hacker going by the alias “Perell” infiltrated BSNL’s systems and released a dataset containing 32,000 lines of sensitive information on the dark web forum, BreachForums. “Perell” claimed that the total number of lines across all databases amounted to over 2.9 million. The compromised data included email addresses, billing details, contact numbers, and other sensitive information, as well as mobile outage records, network details, completed orders, and customer information. On April 24, 2024, “Perell” reposted the database on BreachForums. No motive has been given for the reposting of the information.
