### ISSUE TITLE
ESO Solutions Data Breach: 2.7 Million Individuals Affected

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20281]
https://www.hipaajournal.com/eso-solutions-data-breach/

**Comment by swidup** [comment]
https://healthitsecurity.com/news/healthcare-software-company-notifies-2.7m-individuals-of-data-breach

**Comment by etgifford** [comment]
https://www.paubox.com/news/eso-solutions-announces-data-breach-impacting-15-hospitals
https://www.maine.gov/agviewer/content/ag/985235c7-cb95-4be2-8792-a1252b4f8318/bd939a31-70fd-4f7c-99cf-d6b87906489f.shtml
https://phishingtackle.com/articles/eso-solutions-hit-by-major-ransomware-attack-impacting-2-7-million-patients/

**Comment by etgifford** [comment]
JSON 3bcfa35d-017b-4a65-ac79-cb7670aff23a, ESO Solutions, HQ: Austin, TX, EMP: 722, NAICS: 511210 (Software Publishers), On Sept 17, 2024 hackers gained access to ESO’s systems. This was not discovered until Sept 28, 2024, when suspicious activity was seen on its network. Files were encrypted and files were recovered from backups. The data of 2,700,000 individuals was exfiltrated: names, date of birth, injury and treatment dates and info, contact info, and SSNs. The breach impacted 15 hospitals. Notification letters were sent Dec 12, 2023 and credit monitoring offered through Kroll for 12 months. Two class action lawsuits were filed in January, 2024. The data breach involved the unauthorized access to a protected health information-containing email account belonging to an employee of ESO.

**Comment by alexcpsec-vz** [comment]
Reviewed and added to "submitted"dir
