### ISSUE TITLE
HACKERS CLAIM THEY STOLE DATA OF MORE THAN 2 MILLION INTEGRIS HEALTH PATIENTS

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20293]
https://www.news9.com/story/658a1080d47ad8065ccccffa/hackers-claim-they-stole-data-of-more-than-2-million-integris-health-patients

**Comment by swidup** [comment]
https://www.fourstateshomepage.com/local-news/patient-data-breach-at-oklahoma-hospitals/

**Comment by swidup** [comment]
https://www.hipaajournal.com/integris-health-data-breach/

**Comment by swidup** [comment]
https://www.bleepingcomputer.com/news/security/integris-health-says-data-breach-impacts-24-million-patients/

**Comment by etgifford** [comment]
JSON ce1165e8-89e5-4dd3-a891-5e3241f12400, INTEGRIS Health, HQ: Oklahoma City, OK, EMP: 5,807, NAICS: 621111 (Offices of Physicians (except Mental Health Specialists)). Had a cyberattack on Nov 28, 2023. Attack affects approximately 2,385,646 individuals. On Dec 24, 2024, the hackers sent an email to victims: "Integris Health ([integrisok.com](https://integrisok.com/landing/integrisdoctors?utm_source=MaxConnect&utm_medium=Bing&utm_term=integris%20health&utm_campaign=MaxConnect_SelfBranded&msclkid=4c6eb8bb78101f3aeb5fdd31622f8bf8)) was breached on November 2023. The data of over 2 million patients was compromised including SSN, DOB, Address, Phone, Insurance Information, and Employer Information. This data will sell on the darknet and be used for fraud and identity theft. If you are receiving this message, your data have been compromised. We provide a sample of your data as proof. We have contacted Integris Health, but they refuse to resolve this issue. We give you the opportunity to remove your personal data from our databases before we sell the entire database to data brokers on Jan 5 2024.” The email continues “A buyer can also purchase data without exclusive rights for 3$. In this case, the data will still be listed on the shop. You can remove your data from our shop and protect it from future fraud by purchasing exclusive rights on it (50$)." INTEGRIS is offering one year of monitoring.

**Comment by alexcpsec-vz** [comment]
Added ransomware action without obscuration. Initial actions is Unknown
