### ISSUE TITLE
The Retina Group of Washington Reports Data Breach Exposing Social Security Numbers of Over 455k Patients

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20312]
https://www.prnewswire.com/news-releases/console--associates-pc-the-retina-group-of-washington-reports-data-breach-exposing-social-security-numbers-of-over-455k-patients-302023555.html

**Comment by swidup** [comment]
https://www.hipaajournal.com/retina-group-of-washington-data-breach/

**Comment by etgifford** [comment]
https://www.hipaajournal.com/retina-group-of-washington-data-breach/

**Comment by etgifford** [comment]
JSON ca1f7421-1448-4fdd-bb16-3ad42a71c92d, Retina Group of Washington, HQ: Greenbelt, MD, EMP: 178, NAICS: 62139 (Offices of All Other Health Practitioners), Mar 25, 2023 users started to notice difficulty accessing information on some of its systems. A ransomware attack exposed information of 455935 patients. Data exposed: full names, Social Security numbers, dates of birth, addresses, driver’s license, payment information, insurance information, and health information. Breach report with HHS and notification letters started to get mailed on Dec 22, 2023, nine months after the attack. 
NOTE: Seven Class action lawsuits were filed in Jan 2024 and have been combined into one.

**Comment by etgifford** [comment]
JSON ca1f7421-1448-4fdd-bb16-3ad42a71c92d, Retina Group of Washington, HQ: Greenbelt, MD, EMP: 178, NAICS: 62139 (Offices of All Other Health Practitioners), Mar 25, 2023 users started to notice difficulty accessing information on some of its systems. A ransomware attack exposed information of 455935 patients. Data exposed: full names, Social Security numbers, dates of birth, addresses, driver’s license, payment information, insurance information, and health information. Breach report with HHS and notification letters started to get mailed on Dec 22, 2023, nine months after the attack. 
NOTE: Seven Class action lawsuits were filed in Jan 2024 and have been combined into one.

**Comment by alexcpsec-vz** [comment]
Added Ransomware action. Initial vector is Unknown, not necessarily Hacking.Unknown
