### ISSUE TITLE
Australia's Eagers Automotive finds unauthorized access to parts of IT systems

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20325]
https://www.reuters.com/technology/cybersecurity/australias-eagers-automotive-finds-unauthorized-access-parts-it-systems-2024-01-01/

**Comment by etgifford** [comment]
https://www.bleepingcomputer.com/news/security/eagers-automotive-halts-trading-in-response-to-cyberattack/ https://announcements.asx.com.au/asxpdf/20240102/pdf/05z2t4fb41dwy0.pdf
https://www.bankinfosecurity.com/lockbit-30-claims-attack-on-australian-auto-dealer-eagers-a-24011
https://restoreprivacy.com/lockbit-ransomware-claims-attack-on-australias-largest-car-seller

**Comment by etgifford** [comment]
JSON: e205b503-fd91-426f-9c9d-e472adf24ca5, Eager’s Automotive Limited, HQ:, Brisbane, Australia, EMP: 8500, NAICS: 441110  ( New Car Dealers) On Dec 27, 2023, Eager’s automotive suffered a data breach. As a result, halted trading on the stock exchange. Eagers Automotive is the largest operator of car dealerships in Australia and New Zealand. It also owns a large number of subsidiaries focused on second-hand sales. The data breach affected systems across Australia and New Zealand. On Dec 30, 2023, LockBit 3.0 claimed responsibility and gave Eagers until Jan 19, 2024 to meet their demands or else they will publish all stolen files. Data claimed to be taken: customer data, including names, addresses, contact details, vehicle purchase history, service and repair records, financial details related to vehicle financing or purchases, and possibly preferences or inquiries related to vehicle types, features, or services. On Jan 02, 2024, Eager’s started notifying customers whose information was taken.
