### ISSUE TITLE
Over 340,000 Jason’s Deli customers potentially impacted in credential-stuffing attack 

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#20359]
https://www.scmagazine.com/news/over-340000-jasons-deli-customers-potentially-impacted-in-credential-stuffing-attack

**Comment by swidup** [comment]
https://www.classaction.org/news/jasons-deli-facing-class-action-over-2023-data-breach-affecting-344k-customers

**Comment by etgifford** [comment]
https://www.maine.gov/agviewer/content/ag/985235c7-cb95-4be2-8792-a1252b4f8318/096dbf5d-c589-4289-b05e-f4f91ba0e529.shtml
https://www.classaction.org/news/jasons-deli-facing-class-action-over-2023-data-breach-affecting-344k-customers

**Comment by etgifford** [comment]
JSON 1225704d-788b-47ce-8c84-8fe97302191f, Jason’s Deli, HQ: Beaumont, TX, EMP: 2,064, NAICS: 722511 (Full Service Eating Places). On Dec 31, 2023, suffered a credential stuffing attack affecting 344,034 online “Deli Dollar” customer accounts. Data taken: customers’ names, addresses (including all saved delivery addresses), phone numbers, birthdays, preferred Jason’s Deli locations, order history, contact lists, house account numbers, Deli Dollars points, available redeemable amounts and rewards, and the last four digits of gift card or credit card numbers. (The attack was immediately discovered). The attack was reported to customers Jan 19, 2024. While Jason’s Deli recommended that customers change their usernames and use stronger passwords, it did not say anything about [multi-factor authentication (MFA](https://www.scmagazine.com/perspective/if-multi-factor-authentication-works-so-well-why-doesnt-everyone-use-it)). Jan 24, 2024 a Class Action Lawsuit was filed against Deli Management (Jason’s Deli).

**Comment by alexcpsec-vz** [comment]
Reviewed. Pretty good.
