### ISSUE TITLE
Avis Car Rental Customers Hit By Hack, Data Breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#21025]
https://www.crn.com/news/security/2024/avis-car-rental-customers-hit-by-hack-data-breach

https://www.bleepingcomputer.com/news/security/car-rental-giant-avis-discloses-data-breach-impacting-customers/

**Comment by swidup** [comment]
https://techcrunch.com/2024/09/09/thousands-of-avis-car-rental-customers-had-personal-data-stolen-in-cyberattack/

**Comment by swidup** [comment]
https://www.infosecurity-magazine.com/news/car-giant-avis-breach-300000/

**Comment by etgifford** [comment]
JSON b199822e-b338-4d6b-b2c5-37008efaf156, AVIS Rent A Car System LLC, HQ: Parsippany, NJ, Emp: 24500, NAICS:  532111 (Passenger Car Rental). Avis sent letters to 299,006 customers on Sep 04, 2024 whose information was accessed in a data breach: customer names, mailing addresses, email addresses, phone numbers, dates of birth, credit card numbers and expiration dates, and driver’s license numbers. The breach was discovered Aug 05, 2024 Investigation showed the threat actor accessed a business application on Aug 03, 2024 and Aug 06, 2024. “Insider wrongdoing” was blamed for the breach. Avis is offering one-year credit and identity monitoring through Equifax. Class action lawsuit was filed Sep 18, 2024.

**Comment by alexcpsec-vz** [comment]
Added a hacking step to address the "third-party that gained access". also insider wrongdoing aligns better with Misuse.
