### ISSUE TITLE
[2013] Glens Falls Hospital alerts patients of possible information breach

### ISSUE THREAD

**Issue by hrbrmstr** [vz-risk/VCDB#2958]
http://poststar.com/news/local/glens-falls-hospital-alerts-patients-of-possible-information-breach/article_aba70836-9d6a-11e2-9a0c-0019bb2963f4.html

http://www.lexology.com/library/detail.aspx?g=9f272928-1e5b-4f7a-8d85-ff79eb00c8c5

**Comment by swidup** [comment]
Already coded.
