### ISSUE TITLE
[2013] Maryland officials probe possible abortion link in woman’s death - The Washington Post

### ISSUE THREAD

**Issue by hrbrmstr** [vz-risk/VCDB#3608]
http://www.washingtonpost.com/local/maryland-officials-probe-possible-abortion-link-in-womans-death/2013/02/09/f6bd74c2-7312-11e2-a050-b83a7b35c4b5_story.html

**Comment by swidup** [comment]
This is not a data breach or even a security incident.  Unsure why it was posted.
