### ISSUE TITLE
[2013] Laptop with Olympics plans stolen from car of boxing coach - National News - Independent.ie

### ISSUE THREAD

**Issue by hrbrmstr** [vz-risk/VCDB#3755]
http://www.independent.ie/national-news/laptop-with-olympics-plans-stolen-from-car-of-boxing-coach-3356632.html

**Comment by swidup** [comment]
Dup of https://github.com/vz-risk/VCDB/blob/8c8798f2999fd19330a30ca685fc31994351956b/data/json/validated/16402C78-C1B6-43C8-A871-42F199DEFE49.json
