### ISSUE TITLE
Jewel-Osco hit again by data hack

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#4415]
http://www.chicagotribune.com/business/breaking/chi-jewelosco-hit-by-data-hack-20140929-story.html

http://www.infosecnews.org/ab-acquisition-llc-and-supervalu-inc-annouce-second-hacking-incident-involving-payment-card-data-processing/#.VCr_ckuFr7R

http://www.startribune.com/business/277515921.html?utm_term=OSINT&utm_source=twitterfeed&utm_medium=twitter

**Comment by gdbassett** [comment]
Recorded in offline excel

**Comment by swidup** [comment]
Issue not in json.  Reopening.
