### ISSUE TITLE
Kmart Latest Retail Chain to Disclose Payment Card Breach 

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#4426]
http://threatpost.com/kmart-latest-retail-chain-to-disclose-payment-card-breach/108829

http://www.forbes.com/sites/davelewis/2014/10/14/sears-owned-kmart-discloses-data-breach/?ss=Security

http://go.delicious.com/?id=63408X1518852&xs=1&url=http://krebsonsecurity.com/2014/10/malware-based-credit-card-breach-at-kmart/&sref=https://delicious.com/vzriskteam/agenda

**Comment by gdbassett** [comment]
Created with offline excel.

**Comment by swidup** [comment]
Since this was not put into the corpus, here is an update with impact info:  http://www.reuters.com/article/idUSL1N1AK0BD
