### ISSUE TITLE
Second Reported Data Breach at Shaws

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#4613]
http://www.mychamplainvalley.com/story/d/story/second-reported-data-breach-at-shaws/25999/A0X5XAGek0CohlhGrAj4oA

https://www.google.com/url?rct=j&sa=t&url=http://www.mychamplainvalley.com/story/d/story/shaws-hackers-may-have-stolen-payment-info-from-st/10454/6xhXJQfsb0a-3Pfb3APcgw&ct=ga&cdÊEYAioTNDQ5NTgyMDQxOTA5OTc2MDM1MDIaNDM1NGUxODBkNTBhYzU2ODpjb206ZW46VVM&usg¯QjCNGHM_HI2cQ_AeQKNL3o-bnHLOgA-Q

http://magicvalley.com/news/local/update-supervalu-albertsons-disclose-new-data-breach/article_4627d614-4824-11e4-a185-f784901e5a93.html

**Comment by gdbassett** [comment]
Dupe with https://github.com/vz-risk/VCDB/issues/4415. Closing.
