### ISSUE TITLE
National Organization For Marriage Sues IRS For Leaking Tax Documents To Human Rights Campaign

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#497]
http://www.theglobaldispatch.com/national-organization-for-marriage-sues-irs-for-leaking-tax-documents-to-human-rights-campaign-58294/

**Comment by tecamac** [comment]
http://www.usatoday.com/story/opinion/2013/05/15/irs-commits-political-sabotage-column/2163089/
http://www.hrc.org/press/mitt-romney-fuels-noms-divisive-racial-tactics
http://arc-sos.state.al.us/PEL/SOSELPDF.001/E0090860.PDF
http://nonprofitquarterly.org/2014/06/25/irs-pays-nonprofit-group-50-000-settlement-for-leaking-documents/
