### ISSUE TITLE
Cyberattack on German steel factory causes 'massive damage'

### ISSUE THREAD

**Issue by hrbrmstr** [vz-risk/VCDB#5029]
http://www.itworld.com/article/2861675/cyberattack-on-german-steel-factory-causes-massive-damage.html

**Comment by gdbassett** [comment]
http://www.isssource.com/german-steel-mill-attack-inside-job/

**Comment by tecamac** [comment]
Add Russia attribution: used basic malware short form template need could not input actor. Need to switch to long form

**Comment by swidup** [comment]
You missed the social aspect--this started with a phishing attack.  I corrected the record and added the attribution that you noted.
