### ISSUE TITLE
Data Theft Hits 3.3 Million Borrowers - Educational Credit Management Corp

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5043]
http://www.macroinsider.com/business/data-theft-hits-33-million-borrowers-h2082.html

http://www.macroinsider.com/business/data-theft-hits-33-million-borrowers-h31503.html

**Comment by tecamac** [comment]
broken links

**Comment by nicolasvillatte** [comment]
MacroInsider redirects to WSJ article http://www.wsj.com/articles/SB10001424052702304434404575150024174102954
