### ISSUE TITLE
ID Parts notifies 12,000 customers of payment card breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5073]
http://www.databreaches.net/id-parts-notifies-12000-customers-of-payment-card-breach/

**Comment by gdbassett** [comment]
Coded in offline excel

**Comment by swidup** [comment]
Issue not in json.  Reopening.

**Comment by Spitler** [comment]
removed priority 2016 due to date of breach, included needs review to understand where this was coded.
