### ISSUE TITLE
Morgan Stanley: An employee stole partial client data

### ISSUE THREAD

**Issue by krmaxwell** [vz-risk/VCDB#5090]
http://www.cnbc.com/id/102292464#

> Morgan Stanley said Monday that it terminated an employee for stealing wealth management data from up to 10 percent of its clients.

http://money.cnn.com/2015/01/05/technology/security/morgan-stanley-data-breach/index.html

http://www.bloomberg.com/news/print/2015-01-05/morgan-stanley-fires-employee-accused-of-stealing-client-data.html

**Comment by swidup** [comment]
http://www.marketwatch.com/story/morgan-stanley-shares-down-3-after-employee-theft-of-client-data-2015-01-05
