### ISSUE TITLE
UPS driver's tip leads to arrest of alleged rip-off artist - Liberty Tax Service

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5095]
http://www.gazettetimes.com/philomathexpress/local/ups-driver-s-tip-leads-to-arrest-of-alleged-rip/article_3d6cb6c8-d4a9-5a21-af91-066eb7f31642.html

So buried in this article is this:

Following interviews and phone calls, police learned that the name of a woman living with Upshaw was using the identity of a victim from the robbery of a Liberty Tax Service in Fresno. Various records were stolen, including income tax forms.

**Comment by tecamac** [comment]
coded
