### ISSUE TITLE
French Websites hacked

### ISSUE THREAD

**Issue by bhaskarvk** [vz-risk/VCDB#5173]
http://money.cnn.com/video/news/2015/01/15/french-websites-hacked.cnnmoney/index.html

**Comment by durdur12** [comment]
Close

**Comment by athlos23** [comment]
No its not, please close this if you filed a report on it.

**Comment by swidup** [comment]
http://www.scmagazineuk.com/french-tv-station-apparently-hacked-by-russians-not-isis-sympathisers/article/419756/
