### ISSUE TITLE
Physical Breach Highlights Security Holes at Canada’s Electronic Surveillance Agency

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5200]
http://www.thewhir.com/web-hosting-news/physical-breach-highlights-security-holes-canadas-electronic-surveillance-agency

"The documents also included the identities of several CSE employees, which are usually kept secret, along with contact information."

**Comment by abohman** [comment]
I actually finished this last week, but I forgot to close it.  Sorry.
