### ISSUE TITLE
The Terrasse-Vaudreuil website was hacked by a group claiming to be the Middle East Cyber Army

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5217]
http://full-timewhistle.com/world-21/the-terrasse-vaudreuil-website-was-hacked-by-a-group-claiming-to-be-the-middle-east-cyber-army-4560.html

**Comment by wayneLonnquist** [comment]
The link is inaccessible.

**Comment by tecamac** [comment]
http://www.thestar.com/news/canada/2015/01/23/cyberattack-leaves-small-town-in-quebec-bewildered.html
http://digitallocksmithsinc.com/2015/01/24/terrasse-vaudreuils-website-one-many-hacked/#.Vqnjjo-cGUk
http://montrealgazette.com/news/local-news/terrasse-vaudreuil-website-hacked-by-meca
