### ISSUE TITLE
Jeb Bush just dumped emails, home addresses, and social security numbers of Florida residents online

### ISSUE THREAD

**Issue by krmaxwell** [vz-risk/VCDB#5282]
http://www.theverge.com/2015/2/10/8013531/jeb-bush-florida-email-dump-privacy

**Comment by durdur12** [comment]
closed

**Comment by durdur12** [comment]
Closed

**Comment by blackfist** [comment]
Mohammed, I have added your @durdur12  account to the contributors list so you should be able to close incidents. Looks like I had the wrong username invited.
