### ISSUE TITLE
Embarrassing "data breach" in German payment provider - Novalnet

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5298]
https://translate.google.com/translate?sl=de&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Fderstandard.at%2F2000011722368%2FDatenpanne-bei-Zahlungsanbieter-Betroffene-auch-in-Oesterreich&edit-text=

original link was:  http://derstandard.at/2000011722368/Datenpanne-bei-Zahlungsanbieter-Betroffene-auch-in-Oesterreich

Text:  Security leak transactions made by hundreds of cost online stores - data affected by celebrities such as Udo Lindenberg and Stefanie Hertel

A security breach at a German payment provider has made accessible to all transactions in hundreds of online stores without a password. The reports the journal " Computer Bild "in its latest issue. Among the victims of the "data breach" included the rock musician Udo Lindenberg, folk music star Stefanie Hertel and the German Labour Minister Nahles (SPD).

Hundreds of Sites

From a small wine trade on cosmetics specialist to adult sites were shops across all industries affected. Without much effort, it was possible in the "command center" of the payment provider - claims to be "one of the leading payment service provider" - penetrate, which was largely unsecured obviously accessible.

Conclusions

Also for non-celebrities, it could be uncomfortable when others would have had of such insight into their data: Although the goods ordered were not to be seen, according to "Computer Bild" allowed the unauthorized transactions viewers but quite conclusions. For example, if someone had paid for a contact portal.

The security hole has closed. Whether Austrian business partners or customers of the payment provider were affected initially was not elicit itself. Despite repeated attempts by the APA was no one in the company on Saturday to reach.

Also:  http://www.computerbild.de/artikel/cb-News-Internet-Novalnet-Skandal-11426294.html

The payment service Novalnet schlampte for the safety and thus opened insights into the shopping habits of German users. The victims included many celebrities.

translated link:  https://translate.google.com/translate?sl=de&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Fwww.computerbild.de%2Fartikel%2Fcb-News-Internet-Novalnet-Skandal-11426294.html&edit-text=

**Comment by swidup** [comment]
Another source translated:  https://translate.google.com/translate?sl=de&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Fwww.krone.at%2FDigital%2FLeck_bei_Zahlungsanbieter_Einkaufsdaten_online-Promis_unter_Opfern-Story-439297&edit-text=

**Comment by bizserviceprovider** [comment]
We are trying to contact swidup but no response. The original source of the review is deleted and we are here to address and resolve any complaints may you have.
Kindly share your number or feel free to call back on +1 714 312 3523
we also tried reaching and email on  suzanne.widup@verizonbusiness.com (bouncing)
Also on s_widup@yahoo.com (no response)
called on +1 925 784 6081 several times (no call backs received nor heard back, for the voicemail left).

Awaiting your response.
Regards
