### ISSUE TITLE
7-Eleven the latest victim of credit card skimming

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5305]
http://www.wtsp.com/story/news/local/2015/02/13/card-skimmers-found-on-bradenton-gas-pumps/23342505/

Thanks to a tip from a maintenance worker, Bradenton police were able to locate two credit card skimmers at a Bradenton gas station Thursday afternoon.

Bradenton Police say the worker found the two credit card skimming devices on fuel pumps 1 and 3 while conducting routine maintenance at the 7-Eleven store located at 7407 Manatee Ave. W.

It unknown when the devices were installed and there is no suspect information.

Police say the investigation is ongoing and customers who used the gas pumps recently are asked to notify the Bradenton Police Department should suspicious charges appear on credit or debit card accounts.

Anyone with information on the case is asked to contact Bradenton Detective Nasario Camacho at 941-932-9300, ext. 312, or remain anonymous and eligible for a reward of up to $1,000 by calling Crime Stoppers at 866-634-8477 or send an anonymous E-tip to manateecrimestoppers.com.

**Comment by Usaar** [comment]
Submitted.
