### ISSUE TITLE
UMaine Officials: Computer Containing Student Data Stolen

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5329]
http://wabi.tv/2015/02/18/umaine-officials-computer-containing-student-data-stolen/

http://www.centralmaine.com/2015/02/18/umaine-warns-of-potential-data-breach/

http://www.pressherald.com/2015/02/18/umaine-warns-of-potential-data-breach/

**Comment by Usaar** [comment]
Submitted
