### ISSUE TITLE
Uber security breach may have affected up to 50,000 drivers

### ISSUE THREAD

**Issue by TyIsI** [vz-risk/VCDB#5434]
Uber security breach may have affected up to 50,000 drivers
source: http://www.latimes.com/business/technology/la-fi-tn-uber-data-breach-20150227-story.html

http://thehill.com/policy/cybersecurity/234177-data-breach-hits-uber-driver-info-vulnerable

https://oag.ca.gov/system/files/UBER%20Multistate%20Notice_0.pdf

**Comment by swidup** [comment]
and for more details on their brilliance...  http://arstechnica.com/security/2015/03/in-major-goof-uber-stored-sensitive-database-key-on-public-github-page/

**Comment by swidup** [comment]
http://www.computerworld.com/article/3019928/security/uber-to-pay-20000-in-settlement-over-data-breach.html
