### ISSUE TITLE
Rogers hacked by TeamHans, customer contracts and sensitive corporate e-mails dumped

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5469]
http://www.databreaches.net/ca-rogers-hacked-by-teamhans-customer-contracts-and-sensitive-corporate-e-mails-dumped/

http://www.theglobeandmail.com/report-on-business/rogers-reveals-online-security-breach/article23247719/

http://www.bankinfosecurity.com/hackers-breach-canadian-isp-rogers-a-7971

http://www.pressreader.com/canada/national-post-latest-edition/20150303/282256663955057/TextView

**Comment by durdur12** [comment]
closed
