### ISSUE TITLE
Blue Cross Blue Shield Nurse Accused Of Illegally Accessing Patient Records

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5481]
http://minnesota.cbslocal.com/2015/03/02/blue-cross-blue-shield-nurse-accused-of-illegally-accessing-patient-records/

http://healthitsecurity.com/2015/03/03/potential-hipaa-violation-from-minn-bcbs-nurse/

**Comment by durdur12** [comment]
closed
