### ISSUE TITLE
Two More Health Insurers Report Data Breach - LifeWise

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5575]
http://www.darkreading.com/two-more-health-insurers-report-data-breach/d/d-id/1319511

**Comment by wayneLonnquist** [comment]
same as https://github.com/vz-risk/VCDB/issues/5573
Premera Health insurance was compromised.

**Comment by swidup** [comment]
Went through the record and fixed errors, added additional source.

**Comment by swidup** [comment]
Verify this was coded correctly by Wayne.
