### ISSUE TITLE
March 2015 Security Incident and the Launch of Two Factor Authentication

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5660]
http://slackhq.com/post/114696167740/march-2015-security-incident-and-launch-of-2fa

http://www.ibtimes.com/slack-hacked-leaving-500000-user-emails-exposed-1862146

**Comment by krmaxwell** [comment]
seriously you beat me by 1 minute on this. well done.

**Comment by blackfist** [comment]
coded in SG
