### ISSUE TITLE
Guilty plea entered in fraud, ID theft case - Stockton Unified School District, Calaveras, Contra Costa, El Dorado, Merced, Placer, Sacramento, Stanislaus, Shasta, Santa Clara, Solano, and Yolo County

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5662]
http://www.recordnet.com/article/20150326/NEWS/150329736/101091/A_NEWS

**Comment by blackfist** [comment]
I'm going to disqualify this one because it doesn't say how the actor was able to acquire the information used for identity theft. We don't know if this was hacking, or misuse.
