### ISSUE TITLE
Charges laid under the Health Information Act - Tofield Health Centre

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5704]
http://www.databreaches.net/ca-charges-laid-under-the-health-information-act/

**Comment by Spitler** [comment]
No information provided, admin of databreaches.net said as much as well. Not coding, will check back and see if anything comes out after charges are addressed.

**Comment by swidup** [comment]
No further info has surfaced.  Closing--the court case may eventually give us more data, but that could be years from now.
