### ISSUE TITLE
Harbortouch is Latest POS Vendor Breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5745]
http://krebsonsecurity.com/2015/05/harbortouch-is-latest-pos-vendor-breach/

**Comment by tecamac** [comment]
http://www.bankinfosecurity.com/harbortouch-reveals-pos-malware-attack-a-8128
http://consumerist.com/2015/05/05/big-credit-card-data-breach-hits-bars-and-restaurants-using-harbortouch-point-of-sale-systems/
