### ISSUE TITLE
St. Louis Federal Reserve Forces Password Reset Following DNS Hijacking Attack

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5807]
http://news.softpedia.com/news/St-Louis-Federal-Reserve-Forces-Password-Reset-Following-DNS-Hijacking-Attack-481602.shtml

**Comment by swidup** [comment]
http://krebsonsecurity.com/2015/05/st-louis-federal-reserve-suffers-dns-breach/

**Comment by Spitler** [comment]
Coded 2/1
