### ISSUE TITLE
Hackers Steal Bettys Customer Database

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5808]
http://news.softpedia.com/news/Hackers-Steal-Bettys-Customer-Database-481730.shtml

http://www.misco.co.uk/blog/news/02979/trouble-for-ell-known-yorkshire-tearoom-as-120-thousand-customers-hit-by-data-breach

http://www.theinquirer.net/inquirer/news/2409453/bettys-tea-rooms-admits-data-breach-affecting-120-000-online-cake-munchers

**Comment by kjessen** [comment]
closed 2/4/16
