### ISSUE TITLE
Aussie Telco Telstra Finds Breach in Newly Acquired Data Center Service/ Pacnet

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5809]
http://news.softpedia.com/news/Aussie-Telco-Telstra-Finds-Breach-at-Newly-Acquired-Data-Center-Service-481761.shtml

https://www.google.com/url?rct=j&sa=t&url=http://www.hacksurfer.com/posts/telstra-suffers-data-breach&ct=ga&cdÊEYECoSODk5Njk2NjcyMzI5NDQ4NTEwMhowNjE4OTI4ZTY0YmQyYTE5OmNvbTplbjpVUw&usg¯QjCNGr2TUrwtzPyd1fWMeJiF-fqA6DZw

http://robertjgraham.com/?p=17322

**Comment by swidup** [comment]
http://exchange.telstra.com.au/2015/05/20/pacnet-security-breach/

**Comment by Spitler** [comment]
Coded 2/9
