### ISSUE TITLE
Adult Friend Finder confirms data breach 3.5 million records exposed

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5814]
http://www.csoonline.com/article/2925833/data-breach/adult-friend-finder-confirms-data-breach-3-5-million-records-exposed.html

http://www.bustle.com/articles/85232-hack-of-adultfriendfinder-one-of-the-largest-hookup-sites-exposes-4-million-members-personal-information-from

http://news.softpedia.com/news/Full-Adult-Friend-Finder-Database-Up-for-Sale-for-70-Bitcoins-482157.shtml

**Comment by swidup** [comment]
http://www.channel4.com/news/adult-friendfinder-dating-site-hack-sale-email-data-warning

**Comment by Spitler** [comment]
Coded 2/4
