### ISSUE TITLE
Kolon pleads guilty in Kevlar trade secrets case - DuPont

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5832]
http://www.tirebusiness.com/article/20150522/NEWS/150529962/kolon-pleads-guilty-in-kevlar-trade-secrets-case

**Comment by swidup** [comment]
https://www.fbi.gov/news/stories/2015/august/former-dupont-employee-sentenced

**Comment by Spitler** [comment]
Coded 2/9
