### ISSUE TITLE
Gordagen Pharmaceuticals Wins High Court of Malaysia Judgement for Breach of Confidentiality

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5840]
http://wkrn.membercenter.worldnow.com/story/29120706/gordagen-pharmaceuticals-wins-high-court-of-malaysia-judgement-for-breach-of-confidentiality

**Comment by foleyiii** [comment]
http://www.prnewswire.com/news-releases/gordagen-pharmaceuticals-wins-high-court-of-malaysia-judgement-for-breach-of-confidentiality-300087059.html

**Comment by foleyiii** [comment]
closed - 2/4/2016

**Comment by foleyiii** [comment]
closed - 2/4/2016
