### ISSUE TITLE
Policeman charged with leaking information about Ben Cousins’ arrest to TV reporter girlfriend keeps his job - Perth Police Department

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5850]
http://www.perthnow.com.au/news/western-australia/policeman-charged-with-leaking-information-about-ben-cousins-arrest-to-tv-reporter-girlfriend-keeps-his-job/story-fnhocxo3-1227370169753?nk=36a5b2352efac800cf3ebe3a28539d08

**Comment by Spitler** [comment]
Coded 2/1
