### ISSUE TITLE
Suburban NY Supermarket Customers Targeted In Online Data Breach - Deciccio’s Market

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5875]
http://newyork.cbslocal.com/2015/04/29/deciccios-market-data-breach-ardsley/

**Comment by swidup** [comment]
http://westchester.news12.com/news/decicco-sons-grocery-store-suffers-data-breach-1.10350145

**Comment by foleyiii** [comment]
Closed 2/4/2016
