### ISSUE TITLE
AWOL NUCLEAR SECURITY ‘LEAK’ SUBMARINER SURRENDERS TO POLICE - United Kingdom Royal Navy

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5881]
http://www.breitbart.com/london/2015/05/19/awol-nuclear-security-leak-submariner-surrenders-to-police/

**Comment by swidup** [comment]
http://www.breitbart.com/london/2015/05/18/time-to-renew-trident-navy-whistleblowers-extraordinary-claims-about-dilapidated-nuclear-deterrent/

**Comment by tecamac** [comment]
http://www.theguardian.com/uk-news/2015/jun/17/trident-whistleblower-william-mcneilly-discharged-from-royal-navy
