### ISSUE TITLE
Chinese hackers breach federal government’s personnel office

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#5929]
http://www.washingtonpost.com/world/national-security/chinese-hackers-breach-federal-governments-personnel-office/2015/06/04/889c0e52-0af7-11e5-95fd-d580f1c5d44e_story.html

**Comment by swidup** [comment]
http://www.reuters.com/article/2015/06/06/us-cybersecurity-usa-idUSKBN0OL1V320150606

**Comment by swidup** [comment]
http://www.charlestondailymail.com/article/20150611/ARTICLE/150619767/1276

**Comment by swidup** [comment]
There were two different breaches.  http://www.usnews.com/news/politics/articles/2015/06/15/390-000-people-tied-to-dhs-may-have-had-data-breached

**Comment by swidup** [comment]
http://www.engadget.com/2015/09/02/opm-data-breach-identity-theft-protection/ Credit protection to cost $133 million.

**Comment by tecamac** [comment]
Add China attribution: used short form basic malware template could not input actor attributes

**Comment by swidup** [comment]
I changed the record in the system.  This is closed again. -stw
