### ISSUE TITLE
Irish Bank Resolution Corporation identifies source of leaked bank data

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6000]
http://www.independent.ie/business/irish/ibrc-identifies-source-of-leaked-bank-data-31300734.html

**Comment by tecamac** [comment]
http://www.irishtimes.com/business/financial-services/rt%C3%A9-story-on-o-brien-and-ibrc-based-on-leaked-letter-to-bank-liquidator-1.2210012
