### ISSUE TITLE
Patients' information at risk following security breach at Community Health Centers

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6004]
http://www.wftv.com/news/news/local/patients-information-risk-following-security-breac/nmdWG/

**Comment by swidup** [comment]
http://www.hipaajournal.com/florida-hospital-group-notifies-patients-of-employee-data-theft-7080/

**Comment by gdbassett** [comment]
Issue doesn't have an incident date (required field for incidents).  Response 3103 in vcdb, currently marked 'needs-review'.  If we can find an incident year, we can update it and close it.  Otherwise it'll probably have to remain open.
