### ISSUE TITLE
Navy engineer admits trying to leak plans for new aircraft carrier to Egypt

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6007]
http://www.washingtonpost.com/local/crime/navy-engineer-admits-trying-to-leak-plans-for-new-aircraft-carrier-to-egypt/2015/06/15/dac351a4-0fa2-11e5-adec-e82f8395c032_story.html

**Comment by swidup** [comment]
http://wydaily.com/2015/06/16/local-news-yorktown-naval-engineer-pleads-guilty-to-attempted-espionage/

**Comment by kjessen** [comment]
Closed 2/4/16
