### ISSUE TITLE
Evans Hotels Report Breach to CA OAG

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6121]
https://oag.ca.gov/system/files/Evans%20Hotels%20Substitute%20Notification%20for%20Web%20Posting_0.pdf?

**Comment by swidup** [comment]
http://fox5sandiego.com/2015/07/08/security-breach-at-local-hotels-led-to-unauthorized-charges-on-guests-cards/

**Comment by foleyiii** [comment]
Close 2/5
