### ISSUE TITLE
'How Not to Leave a Law Firm' - Bothwell Bracker

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6140]
http://www.dailyreportonline.com/id=1202731735127/How-Not-to-Leave-a-Law-Firm-Suit-Claims-Wiped-Files-Missing-Clients-Empty-Offices-and-an-I-Quit-Note

**Comment by swidup** [comment]
http://www.abajournal.com/news/article/paid_650k_in_bonuses_2_tort_lawyers_formed_new_firm_left_name_partner_in_em/?utm_source=maestro&utm_medium=email&utm_campaign=weekly_email&job_id=150716BE#A

**Comment by Spitler** [comment]
Use the second link, first is now behind a paywall

**Comment by foleyiii** [comment]
Close 2/4/16

**Comment by foleyiii** [comment]
Closed 2/4/2016
