### ISSUE TITLE
Epic Games forums hit by hack; some user data stolen

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6150]
http://www.zdnet.com/article/epic-games-forum-hit-by-hack-registration-data-stolen/#ftag=RSSbaffb68

**Comment by swidup** [comment]
http://www.bizjournals.com/triangle/blog/techflash/2015/07/epic-games-cary-nc-investigates-data-breach.html

**Comment by foleyiii** [comment]
closed 2/5
