### ISSUE TITLE
Fitch Inadvertently Leaks $1.9 Billion Digital Realty Data Center Deal

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6161]
http://www.forbes.com/sites/antoinegara/2015/07/13/fitch-inadvertently-leaks-1-9-billion-digital-realty-data-center-deal/

**Comment by Spitler** [comment]
Link not behind a paywall or blocked due to having an ad blocker http://www.reuters.com/article/fitch-digitalrealty-idUSL4N0ZT58D20150713

**Comment by Spitler** [comment]
Coded 2/5
