### ISSUE TITLE
Online Cheating Site Ashley Madison Hacked - 30 million accounts affected

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6175]
http://krebsonsecurity.com/2015/07/online-cheating-site-ashleymadison-hacked/

**Comment by swidup** [comment]
http://hosted.ap.org/dynamic/stories/U/US_ASHLEY_MADISON_HACKED?SITE=SCAND&SECTION=HOME&TEMPLATE=DEFAULT

**Comment by swidup** [comment]
http://www.forbes.com/sites/thomasbrewster/2015/07/20/ashley-madison-attack/

**Comment by mdfarhan** [comment]
http://gizmodo.com/the-ashley-madison-hackers-just-released-all-of-their-s-1724920693?utm_campaign=socialflow_gizmodo_facebook&utm_source=gizmodo_facebook&utm_medium=socialflow

**Comment by mdfarhan** [comment]
http://www.wired.com/2015/08/happened-hackers-posted-stolen-ashley-madison-data/

**Comment by swidup** [comment]
http://www.reuters.com/article/2015/08/19/us-ashleymadison-cybersecurity-idUSKCN0QN2BN20150819?feedType=RSS&feedName=technologyNews
