### ISSUE TITLE
ATKINSON, ANDELSON, LOYA, RUUD & ROMO reports breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6206]
https://oag.ca.gov/system/files/Atkinson%2C%20Andelson%2C%20Loya%2C%20Ruud%20%26%20Romo%20Notice_0.pdf

**Comment by swidup** [comment]
http://www.scmagazine.com/personal-data-on-laptop-stolen-from-attorney-with-california-law-firm/article/428222/

**Comment by Spitler** [comment]
Coded 2/5
