### ISSUE TITLE
Georgia Division of Aging Services Accidental disclosure

### ISSUE THREAD

**Issue by planglois925** [vz-risk/VCDB#6217]
The personal data of approximately 3,000 clients of the Community
Care Services Program in Georgia was potentially compromised June 8 after the
Division of Aging Services accidentally emailed the information to a contracted
provider not authorized to view the information. The recipients of the email did not
access the information, and all affected clients have been notified.

Source: http://www.scmagazine.com/breach-affects-3000-clients-enrolled-in-georgiastate-program/article/428766/

**Comment by swidup** [comment]
http://www.bizjournals.com/atlanta/morning_call/2015/07/patient-information-released-in-state-agency-data.html
