### ISSUE TITLE
IT worker gets 10 years for hacking military email - Soto Cano Air Base

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6250]
http://www.washingtontimes.com/news/2015/aug/3/it-worker-gets-10-years-hacking-military-email/

**Comment by swidup** [comment]
http://www.theregister.co.uk/2015/08/03/sysadmin_jailed_10_years_stealing_classified_usaf_docs/

**Comment by foleyiii** [comment]
Closed - 2/4/2016
