### ISSUE TITLE
Carphone Warehouse coughs to MONSTER data breach – 2.4 MEELLION Brits at risk

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6273]
http://www.theregister.co.uk/2015/08/08/carphone_warehouse_data_breach/

**Comment by swidup** [comment]
http://www.databreaches.net/carphone-warehouse-coughs-to-mega-data-breach-hitting-up-to-2-4-meellion-customers/

**Comment by mdfarhan** [comment]
http://www.gagfacts.com/customers-personal-data-breach/

http://www.grantmcgregor.co.uk/2015/carphone-warehouse/
