### ISSUE TITLE
Fred's data breach

### ISSUE THREAD

**Issue by mdfarhan** [vz-risk/VCDB#6307]
http://www.wmcactionnews5.com/story/29825737/protecting-your-payment-card-data-in-the-wake-of-freds-data-breach

**Comment by Spitler** [comment]
http://krebsonsecurity.com/2015/06/discount-chain-freds-inc-probes-card-breach/

**Comment by foleyiii** [comment]
http://www.wsj.com/articles/freds-inc-discloses-cybersecurity-breach-1439248912

**Comment by foleyiii** [comment]
https://www.fredsinc.com/wp-content/uploads/2015/08/FAQ.pdf

**Comment by foleyiii** [comment]
Closed - 2/4/2016
