### ISSUE TITLE
About 2,500 customer credit cards affected in Mohu website breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6414]
http://www.scmagazine.com/about-2500-customer-credit-cards-affected-in-mohu-website-breach/article/437357/

**Comment by swidup** [comment]
http://news.softpedia.com/news/mohu-loses-credit-card-details-for-2-500-clients-during-data-breach-491247.shtml

**Comment by Spitler** [comment]
Coded 2/2
