### ISSUE TITLE
Boston Authorities Exposed Sensitive Data From Automatic License Plate Readers

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6418]
http://news.softpedia.com/news/boston-authorities-exposed-sensitive-data-from-automatic-license-plate-readers-491267.shtml

**Comment by swidup** [comment]
http://www.roadandtrack.com/new-cars/car-technology/news/a26641/boston-license-plate-database-no-password/

**Comment by Spitler** [comment]
Coded 2/1
