### ISSUE TITLE
Cal State data breach hits nearly 80,000 students - We End Violence

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6419]
http://www.latimes.com/local/lanow/la-me-ln-cal-state-data-breach-20150908-story.html

**Comment by swidup** [comment]
Cal State Campuses were:  Channel Islands, Los Angeles, San Bernardino, Maritime Academy, Cal Poly Pomona, Northridge, San Diego and Sonoma

**Comment by swidup** [comment]
http://www.databreaches.net/what-did-csu-do-to-verify-vendors-data-security-and-what-might-ftc-do/

**Comment by swidup** [comment]
http://abc7.com/education/california-state-university-officials-investigating-data-hack-impacting-8-schools/976462/

**Comment by Spitler** [comment]
Coded 2/5
