### ISSUE TITLE
Sutter Health Data Breach Affects 2,500 Patients

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6437]
http://healthitsecurity.com/news/sutter-health-data-breach-affects-2500-patients

**Comment by swidup** [comment]
http://news.sutterhealth.org/2015/09/11/sutter-health-informs-patients-of-unauthorized-document-handling-by-former-billing-unit-employee/

**Comment by dhylender** [comment]
This is a duplicate. I coded the same incident yesterday.
