### ISSUE TITLE
The Kardashians' new websites leaked user names and emails

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6452]
http://www.theverge.com/2015/9/17/9345289/kardashian-website-data-app-leak

**Comment by swidup** [comment]
http://techcrunch.com/2015/09/16/kardashian-website-security-issue-exposes-names-emails-of-over-half-a-million-subscribers-payment-info-safe/

**Comment by Spitler** [comment]
Coded 2/4
