### ISSUE TITLE
Ballantyne man pleads guilty to stealing trade secrets - US Government/Unamed Company

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6503]
http://www.wsoctv.com/news/news/local/ballantyne-man-pleads-guilty-stealing-trade-secret/nnswd/

**Comment by swidup** [comment]
https://www.fbi.gov/charlotte/press-releases/2015/chinese-businessman-charged-with-theft-of-trade-secrets

**Comment by swidup** [comment]
http://www.databreaches.net/chinese-businessman-pleads-guilty-to-theft-of-trade-secrets/ with company names:  "Although the government press releases do not name any of Huang’s employers, Huang’s LinkedIn profile indicates that he worked for CoaLogix in the Charlotte area from February 2012 – March 2014 as a Catalyst Technology Manager. Prior to that, he reports he worked for BASF in New Jersey from 2008 – 2012 as a Staff Engineer, and at Pacific Northwest National Laboratory in Richland, Washington from 2004 – 2008 as a Research Scientist."

**Comment by Spitler** [comment]
Coded 2/2
