### ISSUE TITLE
Chinese Hackers Breached LoopPay, Whose Tech Is Central to Samsung Pay

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6517]
http://www.nytimes.com/2015/10/08/technology/chinese-hackers-breached-looppay-a-contributor-to-samsung-pay.html?_r=0

**Comment by swidup** [comment]
http://news.softpedia.com/news/chinese-hackers-breach-company-that-s-behind-samsung-pay-494069.shtml

**Comment by Spitler** [comment]
Coded 2/1
