### ISSUE TITLE
Prominent US Senators and Mayors Outed as Members of the KKK by Anonymous

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6568]
http://usuncut.com/politics/anonymous-unhoods-kkk-prominent-politicians/

**Comment by swidup** [comment]
http://www.mstarz.com/articles/91035/20151103/anonymous-operation-kkk-data-dump-hoax-politicians-deny-involvement-hackers.htm

**Comment by Spitler** [comment]
This was a hoax
