### ISSUE TITLE
Hungryhouse resets thousands of customers’ passwords

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6710]
http://www.databreaches.net/hungryhouse-resets-thousands-of-customers-passwords/

**Comment by swidup** [comment]
http://www.theregister.co.uk/2015/11/27/hungryhouse_hit_by_data_breach/

**Comment by Spitler** [comment]
Looks like it could be that their customer emails were in a dump from another breach. Not enbough info to code
