### ISSUE TITLE
Health privacy investigation at Wellington Hospital after complaint

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6727]
http://www.databreaches.net/nz-health-privacy-investigation-at-wellington-hospital-after-complaint/

**Comment by swidup** [comment]
http://www.stuff.co.nz/national/health/74591729/health-privacy-investigation-at-wellington-hospital-after-complaint

**Comment by Spitler** [comment]
This is a potential instance of a record being viewed inappropriately. No proof of misuse. Marking as invalid.
