### ISSUE TITLE
Patient records from defunct hospital found in dumpster - Community Hospital / Springfield Regional Medical Center

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6750]
http://www.databreaches.net/oh-patient-records-from-defunct-hospital-found-in-dumpster/

**Comment by swidup** [comment]
http://wdtn.com/investigative-story/hundreds-of-medical-records-found-in-dumpster/

**Comment by kjessen** [comment]
Closed 2/4/16
