### ISSUE TITLE
Tunecore Has Been Hacked, Sensitive Data Revealed, All User Passwords Invalidated

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6759]
http://www.databreaches.net/tunecore-has-been-hacked-sensitive-data-revealed-all-user-passwords-invalidated/

**Comment by swidup** [comment]
http://www.musictimes.com/articles/57447/20151208/tunecore-hacked-millions-musicians-private-information-compromised.htm

**Comment by tecamac** [comment]
http://help.tunecore.com/app/answers/detail/a_id/669
