### ISSUE TITLE
CNIL – Fines Optical Center for Security Violations

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6773]
http://www.winston.com/en/privacy-law-corner/cnil-fines-optical-center-for-security-violations.html

**Comment by swidup** [comment]
Translated link to original breach:  https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Fwww.cnil.fr%2Flinstitution%2Factualite%2Farticle%2Farticle%2Fdefaut-de-securite-de-donnees-clients-sanction-de-50-000-EUR-a-lencontre-doptical-cente%2F&edit-text=

**Comment by Spitler** [comment]
Fines were as a result of an audit that found weaknesses in their web site, but not as a result of a security incident or data breach.
