### ISSUE TITLE
Israeli tunnel hit by cyber attack

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#683]
http://m.apnews.com/ap/db_289563/contentdetail.htm?contentguid=OYbniEK7

http://www.washingtonpost.com/world/middle_east/ap-exclusive-experts-say-hackers-hit-major-israeli-roadway-a-sign-cyber-warfare-now-reality/2013/10/27/54a65a3a-3f2e-11e3-b028-de922d7a3f47_story.html

**Comment by tecamac** [comment]
http://www.usatoday.com/story/tech/2013/10/27/ap-exclusive-israeli-tunnel-hit-by-cyber-attack/3281133/;http://www.nextgov.com/cybersecurity/threatwatch/2013/10/breach/509/;http://thehackernews.com/2013/10/israeli-road-control-system-hacked.html
