### ISSUE TITLE
Skimmers Found at Some Calif., Colo. Safeways

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6831]
http://krebsonsecurity.com/2015/12/skimmers-found-at-some-calif-colo-safeways/

**Comment by Spitler** [comment]
Coded 12/16

**Comment by swidup** [comment]
http://www.securityinfowatch.com/news/12150968/safeway-customers-data-not-compromised-by-skimming-attack

http://almanacnews.com/news/2015/12/18/safeway-denies-bank-card-skimming-at-its-menlo-park-stores
