### ISSUE TITLE
Data Breach on Hello Kitty Servers, Over 3.3 Million Accounts Exposed

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6857]
http://news.softpedia.com/news/data-breach-on-hello-kitty-servers-over-3-3-million-accounts-exposed-497872.shtml

**Comment by tecamac** [comment]
http://www.continuityinsights.com/news/2016/01/hello-kitty-owner-sanrio-says-fan-site-security-leak-fixed (containment 2015-12-22)
http://www.csoonline.com/article/3017171/security/database-leak-exposes-3-3-million-hello-kitty-fans.html (first notification 2015-12-19) 
http://sanriodigital.com/story/security-advisory
