### ISSUE TITLE
Malware-Driven Card Breach at Hyatt Hotels

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6863]
http://krebsonsecurity.com/2015/12/malware-driven-card-breach-at-hyatt-hotels/

http://krebsonsecurity.com/2016/01/hyatt-card-breach-hit-250-hotels-in-50-nations/

**Comment by tecamac** [comment]
http://newsroom.hyatt.com/news-releases?item=123450

**Comment by nicolasvillatte** [comment]
http://www.hyatt.com/protectingourcustomers/

**Comment by nicolasvillatte** [comment]
http://www.scmagazine.com/hyatt-discovers-malware-at-250-hotels/article/465560/
