### ISSUE TITLE
Employee That Stole Yandex's Search Engine Code Gets Off Easy in Court

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6908]
http://news.softpedia.com/news/employee-that-stole-yandex-s-search-engine-code-gets-off-easy-in-court-498199.shtml

**Comment by swidup** [comment]
https://www.searchenginejournal.com/former-yandex-employee-allegedly-tries-to-sell-source-code-on-black-market/147905/

**Comment by Spitler** [comment]
Coded 2/1
