### ISSUE TITLE
GlamGlow report breach to CA OAG

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6915]
http://oag.ca.gov/ecrime/databreach/reports/sb24-58194

**Comment by keithbreland** [comment]
https://oag.ca.gov/system/files/Email%20Notification%20Letter_0.pdf? Notification Email
https://oag.ca.gov/system/files/Mail%20Notification%20Letter_0.pdf? Notification Letter

**Comment by keithbreland** [comment]
7/20
