### ISSUE TITLE
RITA reports personal data of 50,000 taxpayers may be at risk - Regional Income Tax Agency

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6955]
http://fox8.com/2016/01/04/rita-reports-personal-data-of-50000-taxpayers-may-be-at-risk/

**Comment by swidup** [comment]
http://www.cleveland.com/metro/index.ssf/2016/01/rita_loses_personal_info_for_5.html

**Comment by Spitler** [comment]
Coded 2/1
