### ISSUE TITLE
Montreal police scrambling to recover stolen USB drive with sensitive data

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6972]
http://www.cbc.ca/news/canada/montreal/montreal-police-data-theft-1.3395997

**Comment by swidup** [comment]
http://www.cjad.com/cjad-news-community/2016/01/08/theft-of-usb-key-containing-sensitive-data----police-blew-it-tech-expert

**Comment by swidup** [comment]
http://montrealgazette.com/news/local-news/charges-looming-in-theft-of-secret-info-from-montreals-anti-street-gang-police-unit

**Comment by keithbreland** [comment]
7/20
