### ISSUE TITLE
Custodian leaked details of Trump security

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6983]
http://latestworldwidenews.org/metro/2016/01/07/security-details-about-trump-lowell-visit-were-leaked/kfz3kVrZUcU4t4rRGYIfUI/story.html

**Comment by swidup** [comment]
https://www.bostonglobe.com/metro/2016/01/07/security-details-about-trump-lowell-visit-were-leaked/kfz3kVrZUcU4t4rRGYIfUI/story.html

**Comment by keithbreland** [comment]
7/20
