### ISSUE TITLE
Court says cyberattacks struck judicial branch website - Minnesota Judicial Branch

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6985]
http://www.mprnews.org/story/2016/01/08/minnesota-court-website-cyberattack

**Comment by swidup** [comment]
http://news.softpedia.com/news/ddos-attack-on-minnesota-court-system-website-takes-website-offline-for-ten-days-498741.shtml

**Comment by keithbreland** [comment]
7/31
