### ISSUE TITLE
Kean University Hacked Three Times in One Day, Algerian Group Claims Responsibility

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#6999]
http://www.databreaches.net/nj-kean-university-hacked-three-times-in-one-day-algerian-group-claims-responsibility/

**Comment by keithbreland** [comment]
http://unionnewsdaily.com/news/county/21901
Additional information on the Hack of Keen University

**Comment by keithbreland** [comment]
7/20

**Comment by swidup** [comment]
### Additional Source Found

**Source:** https://www.classaction.org/data-breach-lawsuits/kean-university-july-2026
**Headline:** Kean University Data Breach? Attorneys Investigating Hackers' Claims
**Data types:** PII

*Confidence: 60% | Added by vcdb-pipeline*
