### ISSUE TITLE
I hacked Citrix, says Russian hacker w0rm

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#7024]
http://www.scmagazineuk.com/i-hacked-citrix-says-russian-hacker-w0rm/article/464362/

**Comment by swidup** [comment]
http://www.securityweek.com/citrix-says-sensitive-data-not-accessed-breach?utm_source=twitter.com&utm_medium=social&utm_campaign=buffer&utm_content=buffer40639

**Comment by keithbreland** [comment]
7/19
