### ISSUE TITLE
Hackers Compromising and Blackmailing Indian Pharma Companies and Banks

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#7055]
http://www.spamfighter.com/News-20054-Hackers-Compromising-and-Blackmailing-Indian-Pharma-Companies-and-Banks.htm?utm_content=buffer2662d&utm_medium=social&utm_source=facebook.com&utm_campaign=buffer

**Comment by Spitler** [comment]
Coded 2/1.
