### ISSUE TITLE
Flint Hospital Suffers Cyberattack One Day After Anonymous Posts Video Threat

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#7078]
http://news.softpedia.com/news/flint-hospital-suffers-cyberattack-one-day-after-anonymous-posts-video-threat-499403.shtml

**Comment by swidup** [comment]
http://www.beckershospitalreview.com/healthcare-information-technology/january-cyberattack-at-flint-hospital-delayed-patient-care-internal-documents-show.html

**Comment by Spitler** [comment]
I already coded this one.
