### ISSUE TITLE
Waco: Las Vegas man sentenced for ID, VA benefit theft

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#7118]
http://www.kwtx.com/content/news/Waco--Las-Vegas-man-sentenced-for-ID-VA-benefit-theft-366772501.html

**Comment by swidup** [comment]
http://www.kcentv.com/story/31074323/las-vegas-man-sentenced-for-theft-of-va-benefits-aggravated-id-theft-of-bellmead-resident

**Comment by Spitler** [comment]
No organizational victim. This is one man committing ID fraud against another. No information given as to how the PII was obtained.
