### ISSUE TITLE
Ex-Employee Of U.S. Department Of Veteran’s Affairs Sentenced for Aggravated Identity Theft

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#7416]
http://www.databreaches.net/ex-employee-of-u-s-department-of-veterans-affairs-sentenced-for-aggravated-identity-theft/

**Comment by ama0990** [comment]
http://www.stltoday.com/news/local/crime-and-courts/feds-veterans-affairs-employee-stole-veterans-benefits/article_15a60768-963a-5ba9-ac21-83ea79c2de57.html
