### ISSUE TITLE
Norfolk Admirals’ data breach exposes customers’ names, other information

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#7503]
http://www.databreaches.net/norfolk-admirals-data-breach-exposes-customers-names-other-information/

**Comment by swidup** [comment]
http://www.todaysslapshot.com/from-the-ice/echls-norfolk-admirals-suffer-data-breach-exposing-customer-details/

**Comment by gdbassett** [comment]
https://wtkr.com/2016/03/30/norfolk-admirals-taking-action-after-data-breach/

**Comment by gdbassett** [comment]
http://pilotonline.com/news/local/norfolk-admirals-data-breach-exposes-customer-names-other-information/article_17767989-ba18-5362-9118-dc814fb59a19.html
