### ISSUE TITLE
Rigzone Founder Arrested, Allegedly Hacked Data In Wire Fraud Scheme

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#7531]
http://www.rigzone.com/news/oil_gas/a/143807/Rigzone_Founder_Arrested_Allegedly_Hacked_Data_In_Wire_Fraud_Scheme

**Comment by swidup** [comment]
http://www.bizjournals.com/houston/news/2016/03/31/houston-energy-networking-site-founder-arrested.html

**Comment by swidup** [comment]
http://www.chron.com/business/energy/article/Oilpro-shutting-down-months-after-founder-plead-11721198.php

**Comment by keithbreland** [comment]
9/8
