### ISSUE TITLE
FL Dept. of Health Palm Beach County Notification of Breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#7555]
http://www.databreaches.net/fl-dept-of-health-palm-beach-county-notification-of-breach/

**Comment by swidup** [comment]
http://www.databreaches.net/more-details-emerge-on-florida-dept-of-health-palm-beach-county-breach/

**Comment by dhylender** [comment]
I did a search and while there are still no details about how the breach occurred, it appears to me that there is enough detail to include.
