### ISSUE TITLE
Lawsuit claims workers comp insurers hacked into injured workers’ files - HQSU Sign Up Services Inc.

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#7682]
http://www.databreaches.net/lawsuit-claims-workers-comp-insurers-hacked-into-injured-workers-files/

**Comment by ama0990** [comment]
http://www.businessinsurance.com/article/20160425/NEWS08/160429899

**Comment by ama0990** [comment]
http://www.abajournal.com/news/article/insurers_hacked_tens_of_thousands_of_legal_files_to_get_an_edge_in_workers/
