### ISSUE TITLE
Postal worker steals refund checks: Bribed by sophisticated identity theft duo?

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#7712]
http://www.examiner.com/article/postal-worker-steals-refund-checks-bribed-by-sophisticated-identity-theft-duo

**Comment by Robert-Topper** [comment]
http://www.forbes.com/sites/kellyphillipserb/2016/04/29/former-postman-admits-to-stealing-tax-refund-checks-sent-through-the-mail/#630a8c304538
