### ISSUE TITLE
Blue Ridge Surgery Center reports stolen laptop breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#7778]
http://www.blueridgesurgerycenter.com/default/SCA-BllueRidge-SubstituteNotice-051616.pdf

stale link - 10/30/16 AMA

**Comment by ama0990** [comment]
New link: https://www.databreaches.net/nc-stolen-blue-ridge-surgery-center-laptop-was-encrypted-but-password-was-with-it/
