### ISSUE TITLE
Veterans Affairs admits to another privacy breach by Canadian legion staff

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#7815]
http://www.databreaches.net/ca-veterans-affairs-admits-to-another-privacy-breach-by-canadian-legion-staff/

**Comment by ama0990** [comment]
http://news.nationalpost.com/news/canada/canadian-politics/veterans-affairs-admits-to-another-privacy-breach-by-canadian-legion-staff

**Comment by gdbassett** [comment]
Re-opening as SG record (2709) has no attribute data (required for VERIS).  Please fill in and export to a separate spreadsheet.
