### ISSUE TITLE
Hundreds of Australian Websites Attacked for #OpAustralia By Indonesian Hackers, Threats Made To Australia

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#789]
http://www.cyberwarnews.info/2013/11/03/hundreds-of-australian-websites-attacked-for-opaustralia-by-indonesian-hackers/

**Comment by Usaar** [comment]
Link provided goes to a 404 Not Found dead end.
New link (that I'm 99% sure is the same news) - http://phys.org/news/2013-11-anonymous-indonesia-hacks-australia-sites.html

**Comment by Usaar** [comment]
Submitted.
