### ISSUE TITLE
Hacker puts 51 million file sharing accounts for sale on dark web - iMesh

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#7903]
http://www.zdnet.com/article/51-million-imesh-file-sharing-accounts-for-sale-dark-web/

**Comment by swidup** [comment]
http://www.ibtimes.co.uk/imesh-hack-more-51-million-user-records-former-filesharing-site-sale-dark-web-1565185

**Comment by Spitler** [comment]
Coded 6/27
