### ISSUE TITLE
T-Mobile Employee Arrested for Trying to Sell Customer Data

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#7929]
http://www.databreaches.net/cz-t-mobile-employee-arrested-for-trying-to-sell-customer-data/

**Comment by swidup** [comment]
http://www.theregister.co.uk/2016/06/20/tmobile_czech_breach/

**Comment by ama0990** [comment]
http://www.cellular-news.com/story/Operators/68889.php
