### ISSUE TITLE
Business Associate’s Failure to Safeguard Nursing Home Residents’ PHI Leads to $650,000 HIPAA Settlement - Catholic Health Care Services

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8021]
https://www.databreaches.net/business-associates-failure-to-safeguard-nursing-home-residents-phi-leads-to-650000-hipaa-settlement/

**Comment by ama0990** [comment]
http://www.lifehealthpro.com/2016/07/06/cellphone-loss-leads-to-650000-hipaa-settlement
