### ISSUE TITLE
Dr. Douglas Brooks's certificate of registration suspended for 5 months, slapped with $5,000 fine, faces other conditions

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8045]
http://www.saultstar.com/2016/07/04/dr-douglas-brookss-certificate-of-registration-suspended-for-5-months-slapped-with-5000-fine-faces-other-conditions

**Comment by swidup** [comment]
https://www.sootoday.com/local-news/misconduct-found-against-local-doctor-330690

**Comment by ama0990** [comment]
made this two separate incidents in vcdb
