### ISSUE TITLE
Case Note 256145 [2015] NZ PrivCmr 2 : Government agency accidentally discloses informant's identity to employer after workplace complaint

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8050]
https://opcwebsite.cwp.govt.nz/news-and-publications/case-notes-and-court-decisions/case-note-256145-2015-nz-privcmr-2-government-agency-accidentally-discloses-informants-identity-to-employer-after-workplace-complaint/

**Comment by keithbreland** [comment]
9/14
