### ISSUE TITLE
Consulting Firm Levels Computer Fraud, Trade Secret Claims at Ex-Partner - SOAProjects Inc.

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8107]
http://www.therecorder.com/id=1202762825628/Consulting-Firm-Levels-Computer-Fraud-Trade-Secret-Claims-at-ExPartner?slreturn=20160617172651

**Comment by swidup** [comment]
[Consulting Firm Levels Computer Fraud, Trade Secret Claims at Ex-Partner | The Recorder.pdf](https://github.com/vz-risk/VCDB/files/368143/Consulting.Firm.Levels.Computer.Fraud.Trade.Secret.Claims.at.Ex-Partner.The.Recorder.pdf)

**Comment by Robert-Topper** [comment]
fh
