### ISSUE TITLE
Woman sues Pennington County authorities for alleged violation of her civil rights

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8145]
https://www.databreaches.net/woman-sues-pennington-county-authorities-for-alleged-violation-of-her-civil-rights/

**Comment by ama0990** [comment]
http://rapidcityjournal.com/news/local/woman-sues-pennington-county-authorities-for-alleged-violation-of-her/article_e136dc0b-47c3-508a-9f9c-3c1d5354af30.html

**Comment by swidup** [comment]
### Additional Source Found

**Source:** https://www.keloland.com/news/local-news/experts-cyberattack-on-pennington-county-likely-by-foreign-adversary/
**Headline:** Experts: Cyberattack on Pennington County likely by foreign adversary

"Pennington County, South Dakota announced on July 5, 2024, that a cyberattack had crippled portions of its computer network, affecting communications, internet access, and public-facing record-keeping and registration services, though critical services like the sheriff's office, courts, 911 dispatch, and jails remained operational. The county launched a major multi-agency investigation and shut down public access to government services temporarily. Based on the lack of ransom demands and the timing relative to similar attacks in Minnesota, cybersecurity experts quoted in the article assess that a foreign adversary—possibly Iran, China, or Russia—was responsible. County officials stated they would notify any individuals whose personal information was compromised, as required by state law."
**Data types:** Corporate, Government

*Confidence: 85% | Added by vcdb-pipeline*
