### ISSUE TITLE
Patients warned of ‘shocking’ data breach after nurse’s bag stolen from car in Cambridge

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8227]
https://www.databreaches.net/uk-patients-warned-of-shocking-data-breach-after-nurses-bag-stolen-from-car-in-cambridge/

**Comment by swidup** [comment]
Cambridgeshire and Peterborough NHS Foundation Trust (CPFT)

**Comment by swidup** [comment]
http://www.cambridge-news.co.uk/patients-warned-of-8216-shocking-8217-data-breach-after-nurse-8217-s-bag-stolen-from-car-in-cambridge/story-29590054-detail/story.html

**Comment by ama0990** [comment]
https://robertjgraham.com/?p=21069 

contains times of incident
