### ISSUE TITLE
Microsoft Secure Boot key debacle causes security panic

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8256]
http://www.zdnet.com/article/microsoft-secure-boot-key-debacle-causes-security-panic/

**Comment by swidup** [comment]
http://www.techtimes.com/articles/173282/20160811/microsoft-accidentally-leaks-golden-keys-that-unlock-secure-boot-protected-windows-devices-oops.htm

**Comment by swidup** [comment]
"This "golden key" policy, however, was inadvertently shipped out along with retail devices, and discovered by Slipstream and MY123. The policy was deactivated in the devices, but they were included nonetheless."

**Comment by swidup** [comment]
https://www.grc.com/sn/sn-573-notes.pdf

**Comment by my123inindiad** [comment]
https://my123.in/index.php?page=item&id=37
