### ISSUE TITLE
Former Car Dealership Employee Sentenced for her Participation in a Stolen Identity Tax Fraud Scheme

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8366]
https://www.databreaches.net/former-car-dealership-employee-sentenced-for-her-participation-in-a-stolen-identity-tax-fraud-scheme/

**Comment by Robert-Topper** [comment]
http://protectingyourpocket.blog.palmbeachpost.com/2016/06/08/lexus-dealer-worker-convicted-of-id-theft-for-80-of-oxy-pillls/
