### ISSUE TITLE
Columbia County bank customers targeted by ATM skimmers, indictment says - First Niagara, Trustco, & Berkshire Banks

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8426]
http://www.dailyfreeman.com/general-news/20160909/columbia-county-bank-customers-targeted-by-atm-skimmers-indictment-says

**Comment by Robert-Topper** [comment]
First Niagara Bank, Trustco Bank and Berkshire Bank branches in Chatham and Delmar, and Great Barrington, Mass
