### ISSUE TITLE
Hacker tries to ransom housing authority data - Bremerton Housing Authority

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8458]
https://www.databreaches.net/wa-hacker-tries-to-ransom-housing-authority-data/

**Comment by Robert-Topper** [comment]
http://www.kitsapsun.com/news/local/hacker-tries-to-ransom-housing-authority-data-3c7e38bd-2c7a-654d-e053-0100007f4ae1-393487771.html
