### ISSUE TITLE
St. Francis Health System hacked: TheDarkOverlord? (UPDATE)

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8462]
https://www.databreaches.net/st-francis-health-system-hacked-thedarkoverlord/

**Comment by swidup** [comment]
http://www.tulsaworld.com/news/saint-francis-health-system-confirms-data-breach/article_e92d7b77-71f3-542e-aad8-526b9eeade04.html

**Comment by swidup** [comment]
http://www.krmg.com/news/news/local/st-francis-server-gets-hacked-6000-people-affected/nsbhd/

**Comment by Robert-Topper** [comment]
I have been told by a source close to TheDarkOverlord that the Saint Francis hack was not by TheDarkOverlord and that TDO had told him that it wasn’t TDO.
