### ISSUE TITLE
NBTC to probe alleged privacy breach by AIS employee

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8467]
https://www.databreaches.net/th-nbtc-to-probe-alleged-privacy-breach-by-ais-employee/

**Comment by keithbreland** [comment]
http://www.nationmultimedia.com/breakingnews/NBTC-to-probe-alleged-privacy-breach-by-AIS-employ-30295281.html

**Comment by keithbreland** [comment]
9/8
