### ISSUE TITLE
Oxford medical clinic’s server attacked by suspected Russian hackers - Urgent Care Clinic of Oxford

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8546]
http://www.oxfordeagle.com/2016/09/30/oxford-urgent-care-clinic-server-attacked-by-suspected-russian-hackers/

**Comment by swidup** [comment]
https://www.databreaches.net/ms-urgent-care-clinic-of-oxford-notifies-patients-of-ransomware-attack/

**Comment by Spitler** [comment]
I do not have any faith in the details presented in the news article. It appears to sensationalize an opportunistic ransomware into something more sinister (Russia attacks!). Databreaches.net noted 'Actually, there are a number of points that aren’t totally clear. I wish this notification had been written more clearly as to what happened and their response and findings.' I am not comfortable in modeling this either with the details provided in the news article or my inference.
