### ISSUE TITLE
East Baton Rouge school system caught up in bizarre “phishing” email fraud using Superintendent Warren Drake’s name, $46,500 lost in wire transfers

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8727]
https://www.databreaches.net/east-baton-rouge-school-system-caught-up-in-bizarre-phishing-email-fraud-using-superintendent-warren-drakes-name-46500-lost-in-wire-transfers/

**Comment by cdander** [comment]
10/4
