### ISSUE TITLE
Recruitment giant PageGroup hacked, Capgemini dev server blamed for info leak

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8748]
https://www.databreaches.net/open-database-exposes-millions-of-job-seekers-personal-information/

**Comment by swidup** [comment]
http://www.theregister.co.uk/2016/11/11/capgemini_pagegroup_leak/

**Comment by swidup** [comment]
http://www.channelbiz.co.uk/2016/11/14/michael-page-outsourcer-capgemini-suffers-data-breach/

http://www.channelnews.com.au/huge-new-data-leak-details-of-700k-oz-jobseekers-exposed/

**Comment by cdander** [comment]
10/5
