### ISSUE TITLE
Psychological & Counseling Center sends blast email without hiding recipient email addresses - Vanderbilt University Medical Center

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8764]
http://vanderbilthustler.com/news/pcc-sends-blast-email-without-hiding-recipient-email-addresses.html

**Comment by Robert-Topper** [comment]
8747 closed  https://www.databreaches.net/tn-vanderbilt-u-psychological-counseling-center-exposed-students-names-in-email-survey/
