### ISSUE TITLE
Atlantis Provides Notice of Data Security Incident

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8794]
http://www.thebahamasweekly.com/publish/local/Atlantis_Provides_Notice_of_Data_Security_Incident51372.shtml

**Comment by swidup** [comment]
https://www.databreaches.net/atlantis-paradise-island-provides-notice-of-data-security-incident/

**Comment by swidup** [comment]
https://oag.ca.gov/system/files/Atlantis%20notice%20only--%20CA%20Exhibit%201_2_0.pdf?

**Comment by cdander** [comment]
10/5

**Comment by cdander** [comment]
10/5
