### ISSUE TITLE
Stolen laptop leads to potential data security breach in NY - Kineto Rehab PHysical Therapy, PLLC

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8797]
http://healthitsecurity.com/news/physical-therapy-facility-reports-data-security-incident

Note, this article contains multiple breach incidents.  Other breaches are being accounted for in other github issues and can be ignored.

"Stolen laptop leads to potential data security breach in NY

New York-based Kineto Rehab PHysical Therapy, PLLC recently announced on its website that there was a possible data security breach after a bag containing a work laptop was stolen.

Kineto said that it became aware of the missing bag on September 16, 2016, and that the bag was subsequently located but the laptop was not inside. However, footage of the thief has been identified and police are still working to track down the individual.

Patients who were seen for physical therapy services from November 2011 to March 2013 may have had certain information affected. This includes patient names, dates of birth, addresses, Social Security numbers, insurance information and clinical/physical therapy notes.

“There is no indication that your information has been accessed or used by an unauthorized individual,” read the Kineto statement, which was signed by CEO Shirley Agapito, DPT. “Please be assured that we have taken every step necessary to address the incident, and that we are committed to fully protecting all the information that has been entrusted to us.”

Individuals who may have been affected with sensitive information on their file will be offered a complimentary one-year membership identity protection services.

The OCR data breach reporting tool states that 665 individuals may have had their data exposed."

**Comment by cdander** [comment]
9/27
