### ISSUE TITLE
$11M Medicaid fraud ringleader from Charlotte gets 16 years in prison

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8841]
http://www.charlotteobserver.com/news/local/crime/article118183418.html

**Comment by Robert-Topper** [comment]
As part of her scheme, Harlan recruited mental health practitioners, the owners of outpatient mental and behavioral health services companies, patient recruiters and others, Rose said. Fabricated paperwork included nonexistent mental health diagnoses, fake dates of service and phony treatment plans.

Read more here: http://www.charlotteobserver.com/news/local/crime/article118183418.html#storylink=cpy  
Only identity fraud and not required for input to the VCDB.  RT
