### ISSUE TITLE
Las Vegas attorney disappears with millions in client funds, State Bar alleges - Robert Graham

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8880]
http://www.reviewjournal.com/crime/courts/las-vegas-attorney-disappears-millions-client-funds-state-bar-alleges

**Comment by keithbreland** [comment]
https://www.reviewjournal.com/crime/courts/las-vegas-lawyer-pleads-guilty-to-stealing-millions-from-clients/

**Comment by keithbreland** [comment]
9/8
