### ISSUE TITLE
Investigation after Barts Health Trust hit by cyber attack

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#8991]
http://www.standard.co.uk/news/health/barts-health-trust-hit-by-cyber-attack-a3440626.html

**Comment by swidup** [comment]
The Royal London, St Bartholomew's, Whipps Cross and Newham

**Comment by swidup** [comment]
http://www.databreachtoday.com/british-nhs-trust-investigates-suspected-cyberattack-a-9634?mid=1

**Comment by keithbreland** [comment]
8/21
