### ISSUE TITLE
Grey Eagle Casino employee information leaked in major privacy breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9063]
http://globalnews.ca/news/3206136/grey-eagle-casino-employee-information-leaked-in-major-privacy-breach/

**Comment by swidup** [comment]
http://globalnews.ca/news/3208546/security-experts-call-grey-eagle-casino-security-breach-a-wake-up-call/

**Comment by keithbreland** [comment]
8/18
