### ISSUE TITLE
Break-in prompts hospital to assess possible patient privacy breach - Bluewater Health / Sarnia General Hospital

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9064]
https://www.databreaches.net/ca-break-in-prompts-hospital-to-assess-possible-patient-privacy-breach/

**Comment by swidup** [comment]
http://thesarniajournal.ca/privacy-breach-at-hospital-under-investigation/

**Comment by keithbreland** [comment]
8/25
