### ISSUE TITLE
Someone Is Selling Coachella User Accounts on the Dark Web

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9267]
https://motherboard.vice.com/en_us/article/someone-is-selling-coachella-user-accounts-on-the-dark-web

**Comment by swidup** [comment]
http://www.konbini.com/us/entertainment/coachella-confirms-user-info-stolen-website-2017/

**Comment by swidup** [comment]
http://www.billboard.com/articles/business/7736621/goldenvoice-offering-hacking-victims-free-identity-protection-services

**Comment by keithbreland** [comment]
7/25
