### ISSUE TITLE
Little Monsters: User data from Lady Gaga's social network are supposed to be leased

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9312]
https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fwww.heise.de%2Fsecurity%2Fmeldung%2FLittle-Monsters-Nutzerdaten-aus-Lady-Gagas-Social-Network-sollen-geleakt-sein-3646447.html&edit-text=

**Comment by swidup** [comment]
Untranslated link:  https://www.heise.de/security/meldung/Little-Monsters-Nutzerdaten-aus-Lady-Gagas-Social-Network-sollen-geleakt-sein-3646447.html

**Comment by Spitler** [comment]
zero details on threat action.
