### ISSUE TITLE
Police: Verizon Employees Used Stolen Info to Buy Phones - Locklear Dodge.

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9333]
https://www.usnews.com/news/best-states/alabama/articles/2017-03-02/police-verizon-employees-used-stolen-info-to-buy-phones

**Comment by keithbreland** [comment]
http://www.tuscaloosanews.com/news/20170301/3-women-charged-with-trafficking-stolen-identities

**Comment by keithbreland** [comment]
7/18
