### ISSUE TITLE
Thousands of NHS Wales staff lose personal data in breach - Landauer

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9349]
https://www.scmagazineuk.com/thousands-of-nhs-wales-staff-lose-personal-data-in-breach/article/643803/

**Comment by swidup** [comment]
https://www.theregister.co.uk/2017/03/13/thousands_of_nhs_staff_details_lost_in_breach_of_it_contractors_server/

**Comment by swidup** [comment]
https://www.digitalhealth.net/2017/03/thousands-more-nhs-staff-have-their-data-compromised-by-landauer-hack/

**Comment by swidup** [comment]
http://businessnewswales.com/nhs-waless-data-hacking-scandal-shows-disastrous-impact-cyber-security-breach/

**Comment by swidup** [comment]
http://www.chesterchronicle.co.uk/news/chester-cheshire-news/data-breach-affects-countess-chester-12863877

**Comment by cdander** [comment]
12/19
