### ISSUE TITLE
Computer Hackers Again Gain Access to Athletes’ Private Medical Records - International Association of Athletics Federations

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9407]
https://www.nytimes.com/2017/04/03/sports/computer-hackers-again-gain-access-to-athletes-private-medical-records.html

**Comment by swidup** [comment]
http://www.insidethegames.biz/articles/1048848/iaaf-fear-athlete-data-theft-after-hack-by-fancy-bears

**Comment by keithbreland** [comment]
7/19
