### ISSUE TITLE
Gamestop website hacked 

### ISSUE THREAD

**Issue by josdavi2** [vz-risk/VCDB#9445]
http://www.pcworld.com/article/3188558/security/lengthy-gamestop-hack-may-have-compromised-customer-credit-cards-personal-info.html -- Gamestop website likely hacked and Credit card nabbers were able to get away with names, addresses, credit card numbers, expiration dates, and the three-digit card verification values (CVV) on the back of cards. Looks like the hackers used malware infecting an e-tailer’s site to intercept the information before it’s encrypted and processed.

**Comment by josdavi2** [comment]
Gamestop website likely hacked and Credit card nabbers were able to get away with names, addresses, credit card numbers, expiration dates, and the three-digit card verification values (CVV) on the back of cards. Looks like the hackers used malware infecting an e-tailer’s site to intercept the information before it’s encrypted and processed.

**Comment by swidup** [comment]
Duplicate of #9425
Gamestop.com Investigating Possible Breach
Opened by swidup on Apr 7
