### ISSUE TITLE
Dallas Tornado siren hacked 

### ISSUE THREAD

**Issue by josdavi2** [vz-risk/VCDB#9446]
https://www.washingtonpost.com/news/the-intersect/wp/2017/04/09/someone-hacked-every-tornado-siren-in-dallas-it-was-loud/?utm_term=.09849744ea16 – some one hacked every emergency siren in Dalles. Officials have ruled out a remote hack — telling reporters someone gained physical access to a hub connecting all the sirens. This is single incident believed to be first of its kind for a city wide hack

**Comment by josdavi2** [comment]
some one hacked every emergency siren in Dalles. Officials have ruled out a remote hack — telling reporters someone gained physical access to a hub connecting all the sirens. This is single incident believed to be first of its kind for a city wide hack

**Comment by cdander** [comment]
11/7
