### ISSUE TITLE
Prisoners built two PCs from parts, hid them in ceiling, connected to the state's network and did cybershenanigans - Ohio Department of Rehabilitation and Correction

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9460]
https://www.theregister.co.uk/2017/04/12/prisoners_built_computer_connected_to_states_network/?utm_source=dlvr.it&utm_medium=facebook

**Comment by keithbreland** [comment]
https://regmedia.co.uk/2017/04/12/ohio_inspector_general_report.pdf

**Comment by keithbreland** [comment]
8/16
