### ISSUE TITLE
Province mailed private information to strangers - Ontario Ministry of Government and Consumer Services 

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9505]
http://www.therecord.com/news-story/7285929-province-mailed-private-information-to-strangers/

**Comment by swidup** [comment]
http://www.municipalinfonet.com/detail_news.php?ID=636326&titre=Government+scrambling+after+printing+mistake+causes+data+breach+affecting+thousands&cat=;66

**Comment by cdander** [comment]
12/19
