### ISSUE TITLE
Unauthorized EHR Access Potentially Exposes 14K Records - Diamond Institute for Infertility and Menopaus

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9523]
http://healthitsecurity.com/news/unauthorized-ehr-access-potentially-exposes-14k-records

**Comment by swidup** [comment]
http://www.doj.nh.gov/consumer/security-breaches/documents/diamond-20170428.pdf

**Comment by cdander** [comment]
12/18

**Comment by swidup** [comment]
https://www.databreaches.net/nj-acting-ag-bruck-announces-settlement-with-fertility-clinic-over-cybersecurity-lapses-and-data-breach/  Reopening for impact and the fact that it is not in the dataset.
