### ISSUE TITLE
Trios Health fires employee over records breach, hundreds of patients affected

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9535]
http://www.tri-cityherald.com/news/local/article153344574.html

**Comment by swidup** [comment]
O: Trios Health; A1: I; A2: PM; A3: Database; A4: C; Sum: "A Trios Health employee improperly accessed the electronic medical records of about 600 patients over 3 1/2 years, the Kennewick health system announced Tuesday morning.

The records may have included information related to Trios Health visits, not including visits to outpatient Trios Medical Group providers, as well as diagnoses, demographic information such as addresses, phone numbers and driver’s license numbers, and also social security numbers, Trios officials said in a statement.  The improper access happened between October 2013 and March 2017, and came to light after Rice came on board to provide patient information and compliance oversight.";

**Comment by cdander** [comment]
12/18
