### ISSUE TITLE
Memory stick led to stolen computer - Nottinghamshire Police

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9538]
http://newarkadvertiser.co.uk/news/2017/05/26/memory-stick-led-to-stolen-computer

**Comment by swidup** [comment]
A1: I; A2: Physical, Theft; A3: Desktop, Thumbdrive; Sum: "A memory stick dropped in a supermarket carpark led to the discovery of a computer, stolen from Nottinghamshire Police, in the home of one its intelligence analysts."

**Comment by cdander** [comment]
11/6
