### ISSUE TITLE
Arizona Department of Health Services notifies 2,500 of possible info breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9544]
http://www.havasunews.com/news/az-health-dept-notifies-of-possible-info-breach/article_1fd871e6-4329-11e7-a4b2-9f7e62dc9ed1.html

**Comment by swidup** [comment]
http://www.beckershospitalreview.com/healthcare-information-technology/arizona-health-department-2-5k-patients-phi-lost-in-mail.html

**Comment by cdander** [comment]
12/13
