### ISSUE TITLE
Plastic surgery patients face extortion in wake of clinic data breach - Grozio Chirurgija

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9551]
https://www.theregister.co.uk/2017/05/31/plastic_surgery_extortion_hack/

**Comment by swidup** [comment]
https://www.tripwire.com/state-of-security/latest-security-news/hackers-leak-personal-data-photos-cosmetic-surgery-clinic/

**Comment by cdander** [comment]
12/13
