### ISSUE TITLE
Ransomware virus attack at Sawai Man Singh (SMS) Hospital in Jaipur: OPD partially operational now

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9618]
https://www.pinkcitypost.com/ransomware-virus-attack-sms-hospital-jaipur-opd-partially-operational-now/

**Comment by keithbreland** [comment]
http://timesofindia.indiatimes.com/city/jaipur/ransomware-virus-attack-hits-services-at-sms-hospital/articleshow/59062261.cms

Previous link is no longer working.

**Comment by keithbreland** [comment]
7/28
