### ISSUE TITLE
The Lowest Scam - Seattle Cancer Care Alliance

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9668]
http://www.nbcnews.com/id/10584944/ns/dateline_nbc/t/lowest-scam/

**Comment by swidup** [comment]
https://www.law.uh.edu/healthlaw/perspectives/2007/(DM)HIPAACrimCharges.pdf

**Comment by keithbreland** [comment]
Not eligible Credit Card Fraud happened in 2004 and 2003. 
7/31.
