### ISSUE TITLE
Self-Service Food Kiosk Vendor Avanti Hacked

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9732]
https://krebsonsecurity.com/2017/07/self-service-food-kiosk-vendor-avanti-hacked/

**Comment by swidup** [comment]
https://www.theregister.co.uk/2017/07/10/malware_scum_snack_on_lunchroom_kiosks/

**Comment by keithbreland** [comment]
http://www.avantimarkets.com/notice-of-data-breach/?utm_source=avantiwebsite&utm_medium=breach&utm_campaign=databreach

Company Breach Letter to Customers

**Comment by keithbreland** [comment]
7/19
