### ISSUE TITLE
Almost 12,000 Records Compromised in Two New Ransomware Attacks - PVHS-ICM Employee Health and Wellness, GI Care for Kids Endoscopy Center

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9743]
http://www.hipaajournal.com/almost-12000-records-compromised-ransomware-attacks-8878/

**Comment by swidup** [comment]
Code as two separate cases.

**Comment by swidup** [comment]
https://dojmt.gov/wp-content/uploads/PVHS-ICM-Employee-Health-and-Wellness.pdf  source doc for the first case.

**Comment by keithbreland** [comment]
9/8
