### ISSUE TITLE
Paramedic who stole debit card from dead man wants lighter sentence - Santa Fe Fire Department

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9745]
https://www.abqjournal.com/1031083/paramedic-who-stole-debit-card-from-dead-man-wants-lighter-sentence.html

**Comment by swidup** [comment]
https://www.abqjournal.com/755997/santa-fe-paramedic-accused-of-stealing-using-dead-mans-debit-card.html?utm_source=abqjournal.com&utm_medium=related+posts+-+crime&utm_campaign=related+posts

**Comment by keithbreland** [comment]
8/15
