### ISSUE TITLE
Bupa loses personal details of 108,000 people in data breach

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9754]
http://www.telegraph.co.uk/technology/2017/07/13/bupa-loses-personal-details-108000-people-data-breach/

**Comment by swidup** [comment]
https://www.theregister.co.uk/2017/07/13/bupa_data_breach/

**Comment by keithbreland** [comment]
7/18

**Comment by swidup** [comment]
http://www.smartcompany.com.au/technology/data-breach-at-health-insurer-bupa-affects-500000-customer-records-in-deliberate-act-by-rogue-employee/  The record needs to be updated with new record count.

**Comment by swidup** [comment]
Created an update record.
