### ISSUE TITLE
Dow Jones Leaks Personal Info of 2.2 Million Customers

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9765]
https://www.infosecurity-magazine.com/news/dow-jones-leaks-personal-info/

**Comment by swidup** [comment]
Also affected:  The Wall Street Journal and Barron's  https://www.usatoday.com/story/tech/news/2017/07/17/wall-street-journal-parent-exposes-2-2-m-customers-data-cloud-storage-leak/485604001/

**Comment by keithbreland** [comment]
7/18
