### ISSUE TITLE
Wells Fargo Accidentally Releases Trove of Data on Wealthy Clients

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9789]
https://www.nytimes.com/2017/07/21/business/dealbook/wells-fargo-confidential-data-release.html

**Comment by keithbreland** [comment]
7/27

**Comment by swidup** [comment]
http://www.abajournal.com/news/article/lawyers_e_discovery_error_led_to_release_of_confidential_wells_fargo_client#When:14:20:00Z
