### ISSUE TITLE
Kansas Department of Commerce data breach compromised millions of Social Security numbers In 10 States

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9792]
http://www.gctelegram.com/news/20170720/kansas-data-breach-compromised-millions-of-social-security-numbers-in-10-states

**Comment by swidup** [comment]
http://www.ibtimes.com/kansas-data-breach-exposes-more-5-million-social-security-numbers-2569024

**Comment by keithbreland** [comment]
8/2
