### ISSUE TITLE
PARIS TN: 911 director Archer confirms ransomware hack from last year - Henry County’s Enhanced 911

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9806]
http://www.parispi.net/news/local_news/article_b8941e24-6cb1-11e7-8821-abac5e9986bd.html

**Comment by swidup** [comment]
http://fox17.com/news/local/fox-17-investigates-cyber-attacks-block-911-calls-in-tennessee-around-the-us

**Comment by keithbreland** [comment]
9/8
