### ISSUE TITLE
Sweden exposed sensitive data on citizens, military personnel - Swedish Transport Authority

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9810]
https://www.itnews.com.au/news/sweden-exposed-sensitive-data-on-citizens-military-personnel-469046

**Comment by swidup** [comment]
https://www.bleepingcomputer.com/news/government/biggest-data-leak-in-swedens-history-punished-with-half-a-months-paycheck/

**Comment by keithbreland** [comment]
8/25
