### ISSUE TITLE
Wilmington doctor indicted on insurance fraud and identity theft charges - Dr. Karl McIntosh

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9852]
http://www.delawareonline.com/story/news/crime/2017/07/27/wilmington-delware-doctor-indicted-insurance-fraud-and-identity-theft/516118001/

**Comment by swidup** [comment]
https://good-assurance.com/wilmington-doctor-indicted-on-insurance-fraud-and-identity-theft/

**Comment by keithbreland** [comment]
8/2
