### ISSUE TITLE
Fine for former garda who "wrote own P45" by leaking information

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9864]
http://www.irishexaminer.com/breakingnews/ireland/fine-for-former-garda-who-quotwrote-own-p45quot-by-leaking-information-799913.html

**Comment by swidup** [comment]
http://www.independent.ie/irish-news/courts/garda-passed-on-highly-sensitive-information-from-pulse-35979131.html

**Comment by Spitler** [comment]
Coded 8/3
