### ISSUE TITLE
WestJet data breach reveals customer profile information

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9866]
http://calgaryherald.com/news/local-news/westjet-data-breach-reveals-customer-profile-information

**Comment by Spitler** [comment]
Let's wait and see if any solid information comes from this. Too early to code with any amount of detail.

**Comment by swidup** [comment]
http://www.cbc.ca/news/canada/calgary/westjet-privacy-breach-rewards-members-1.4227534
