### ISSUE TITLE
France: Data Protection Agency to impose fines for data breach for the first time - Hertz

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9867]
https://www.heise.de/newsticker/meldung/Frankreich-Datenschutzbehoerde-verhaengt-erstmals-Geldstrafe-fuer-Datenpanne-3786244.html?wt_mc=rss.ho.beitrag.atom

**Comment by swidup** [comment]
From google translate:  "The car rental company Hertz has to pay 40,000 euros to the French state, because data from more than 35,000 customers were accessible through its website. The CNIL control authority is thus using new sanctions for the first time.

Since November, the Commission Nationale de l'Informatique et des Libertés (CNIL) has been able to impose fines on data protection violations in accordance with the law for a digital republic, The French data protection authority has now made use of this new option for the first time and has thrown the car rental company Hertz to pay a 40,000 euro penalty.

His offense was that in October personal data such as name, contact details and driving license numbers were freely accessible from 35,357 users of the website www.cartereduction-hertz.com, as the supervisory authority announced on Thursday. Holders of a discount card of the company can make use of the portal benefits. Employees of the CNIL had learned by a reference of the leak. They immediately informed Hertz of the find. The responsible parties there were alarmed by the contractor, who was responsible for the development of the site. This had immediately taken the necessary steps to fill the data leak.

Problem fixed quickly
In more detailed investigations, the investigators found that the breakdown was the result of a fault during a server change. A code line had been deleted, so that the completed forms of the participants in the discount program could be displayed again. In the case of the sanction procedure and the sentence imposed on the French subsidiary of the US group, the CNIL has, in its view, taken into account the fact that the car translator has responded quickly, worked well with the Office and initiated a comprehensive data protection audit."

**Comment by swidup** [comment]
https://www.connexionfrance.com/French-news/Hertz-France-must-pay-40-000-fine-in-new-digital-law

**Comment by Spitler** [comment]
8/3 coded.
