### ISSUE TITLE
Bengaluru techie arrested for data theft from Aadhaar website - Ola

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9922]
http://economictimes.indiatimes.com/small-biz/security-tech/security/ola-employee-arrested-for-data-theft-from-aadhaar-website/articleshow/59909079.cms

**Comment by swidup** [comment]
http://timesofindia.indiatimes.com/city/bengaluru/aadhaar-e-kyc-app-had-88000-downloads-cyber-police/articleshow/59976640.cms

**Comment by keithbreland** [comment]
9/14
