### ISSUE TITLE
In A Shocking Breach, Aadhaar Details Of A Million Pensioners Leaked In Jharkhand

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9926]
http://www.huffingtonpost.in/2017/04/22/in-a-shocking-breach-aadhaar-details-of-a-million-pensioners-le_a_22051319/

**Comment by swidup** [comment]
https://nakedsecurity.sophos.com/2017/05/03/concern-mounts-at-indian-id-scheme-as-portals-leak-100m-peoples-details/

**Comment by keithbreland** [comment]
https://cis-india.org/internet-governance/information-security-practices-of-aadhaar-or-lack-thereof-a-documentation-of-public-availability-of-aadhaar-numbers-with-sensitive-personal-financial-information-1

**Comment by keithbreland** [comment]
9/8
