### ISSUE TITLE
IT head of hospital, former employee booked for data theft - Narmada Hospital

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9994]
http://indiatoday.intoday.in/story/it-head-of-hospital-former-employee-booked-for-data-theft/1/1020758.html

**Comment by swidup** [comment]
http://thehitavada.com/Encyc/2017/8/8/First-case-of-data-theft-at-hospital.aspx

**Comment by keithbreland** [comment]
8/29
