### ISSUE TITLE
Pa. Nurse Admits He Filmed Female Patients — Including Teen Girl — While They Were Undressed - Penn Medicine

### ISSUE THREAD

**Issue by swidup** [vz-risk/VCDB#9997]
http://people.com/crime/pennsylvania-nurse-filmed-naked-female-patients/

**Comment by swidup** [comment]
https://www.cbsnews.com/news/pa-nurse-pleads-guilty-to-secretly-recording-female-patients/

**Comment by keithbreland** [comment]
8/29
